// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: permission_service.proto
#ifndef GRPC_permission_5fservice_2eproto__INCLUDED
#define GRPC_permission_5fservice_2eproto__INCLUDED

#include "permission_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ottx {
namespace permission {

// gRPC service for enumerating application permissions.
class AppPermissionsService final {
 public:
  static constexpr char const* service_full_name() {
    return "ottx.permission.AppPermissionsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of permissions for the specified application.
    virtual ::grpc::Status EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::ottx::permission::EnumeratePermissionsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>> AsyncEnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>>(AsyncEnumeratePermissionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>> PrepareAsyncEnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>>(PrepareAsyncEnumeratePermissionsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Returns the list of permissions for the specified application.
      virtual void EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>* AsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::permission::EnumeratePermissionsResponse>* PrepareAsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::ottx::permission::EnumeratePermissionsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>> AsyncEnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>>(AsyncEnumeratePermissionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>> PrepareAsyncEnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>>(PrepareAsyncEnumeratePermissionsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, std::function<void(::grpc::Status)>) override;
      void EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* AsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* PrepareAsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EnumeratePermissions_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of permissions for the specified application.
    virtual ::grpc::Status EnumeratePermissions(::grpc::ServerContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnumeratePermissions(::grpc::ServerContext* context, ::ottx::permission::EnumeratePermissionsRequest* request, ::grpc::ServerAsyncResponseWriter< ::ottx::permission::EnumeratePermissionsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EnumeratePermissions<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response) { return this->EnumeratePermissions(context, request, response); }));}
    void SetMessageAllocatorFor_EnumeratePermissions(
        ::grpc::MessageAllocator< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnumeratePermissions(
      ::grpc::CallbackServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EnumeratePermissions<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnumeratePermissions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EnumeratePermissions(context, request, response); }));
    }
    ~WithRawCallbackMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnumeratePermissions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EnumeratePermissions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EnumeratePermissions() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse>* streamer) {
                       return this->StreamedEnumeratePermissions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EnumeratePermissions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EnumeratePermissions(::grpc::ServerContext* /*context*/, const ::ottx::permission::EnumeratePermissionsRequest* /*request*/, ::ottx::permission::EnumeratePermissionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnumeratePermissions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ottx::permission::EnumeratePermissionsRequest,::ottx::permission::EnumeratePermissionsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EnumeratePermissions<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EnumeratePermissions<Service > StreamedService;
};

}  // namespace permission
}  // namespace ottx


#endif  // GRPC_permission_5fservice_2eproto__INCLUDED
