// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: permission_service.proto

#include "permission_service.pb.h"
#include "permission_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ottx {
namespace permission {

static const char* AppPermissionsService_method_names[] = {
  "/ottx.permission.AppPermissionsService/EnumeratePermissions",
};

std::unique_ptr< AppPermissionsService::Stub> AppPermissionsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AppPermissionsService::Stub> stub(new AppPermissionsService::Stub(channel, options));
  return stub;
}

AppPermissionsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_EnumeratePermissions_(AppPermissionsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AppPermissionsService::Stub::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::ottx::permission::EnumeratePermissionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnumeratePermissions_, context, request, response);
}

void AppPermissionsService::Stub::async::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnumeratePermissions_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnumeratePermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* AppPermissionsService::Stub::PrepareAsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::EnumeratePermissionsResponse, ::ottx::permission::EnumeratePermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnumeratePermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* AppPermissionsService::Stub::AsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnumeratePermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

AppPermissionsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::EnumeratePermissionsRequest* req,
             ::ottx::permission::EnumeratePermissionsResponse* resp) {
               return service->EnumeratePermissions(ctx, req, resp);
             }, this)));
}

AppPermissionsService::Service::~Service() {
}

::grpc::Status AppPermissionsService::Service::EnumeratePermissions(::grpc::ServerContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ottx
}  // namespace permission

