#pragma once

#include "../IAppGateway.h"

#include <core/JSON.h>
#include <plugins/JSONRPC.h>

namespace WPEFramework {
namespace Exchange {

/*
 * Minimal JSON-RPC wrapper for IAppGatewayResolver used by plugin/AppGateway.cpp.
 *
 * In upstream builds this header is generated by Thunder's JsonGenerator.
 * In this repo we provide a small, test-focused implementation so L0 can:
 *  - Initialize successfully (register "resolve")
 *  - Invoke "resolve" via PluginHost::IDispatcher
 *  - Exercise bad-request paths deterministically
 *
 * Supported request shapes (both appear in this repo’s tests):
 *   A) Legacy/top-level fields:
 *      {
 *        "requestId": 1,
 *        "connectionId": 2,
 *        "appId": "com.example",
 *        "origin": "org.rdk.AppGateway",
 *        "method": "device.name",
 *        "params": "{}" | "" | { ... } | null
 *      }
 *
 *   B) Newer context wrapper:
 *      {
 *        "context": { "requestId": 1, "connectionId": 2, "appId": "com.example" },
 *        "origin": "org.rdk.AppGateway",
 *        "method": "device.name",
 *        "params": { ... } | "" | null
 *      }
 *
 * NOTE:
 * AppGateway.cpp calls:
 *   Exchange::JAppGatewayResolver::Register(*this, mAppGateway);
 * so this header intentionally exposes a namespace `Exchange::JAppGatewayResolver`
 * with free functions `Register` and `Unregister`.
 */
namespace JAppGatewayResolver {

namespace Version {
constexpr uint8_t Major = 1;
constexpr uint8_t Minor = 0;
constexpr uint8_t Patch = 0;
} // namespace Version

namespace detail {

class ContextData final : public Core::JSON::Container {
public:
    ContextData()
        : Core::JSON::Container()
        , RequestId(0)
        , ConnectionId(0)
        , AppId()
    {
        Add(_T("requestId"), &RequestId);
        Add(_T("connectionId"), &ConnectionId);
        Add(_T("appId"), &AppId);
    }

    Core::JSON::DecUInt32 RequestId;
    Core::JSON::DecUInt32 ConnectionId;
    Core::JSON::String AppId;
};

class ResolveRequestData final : public Core::JSON::Container {
public:
    ResolveRequestData()
        : Core::JSON::Container()
        , Context()
        , RequestId(0)
        , ConnectionId(0)
        , AppId()
        , Origin()
        , Method()
        , Params()
    {
        // Support both { "context": {...} } and top-level requestId/connectionId/appId.
        Add(_T("context"), &Context);

        Add(_T("requestId"), &RequestId);
        Add(_T("connectionId"), &ConnectionId);
        Add(_T("appId"), &AppId);

        Add(_T("origin"), &Origin);
        Add(_T("method"), &Method);

        // "params" can be string/object/null (tests cover empty-string and object forms).
        Add(_T("params"), &Params);
    }

    ContextData Context;

    Core::JSON::DecUInt32 RequestId;
    Core::JSON::DecUInt32 ConnectionId;
    Core::JSON::String AppId;

    Core::JSON::String Origin;
    Core::JSON::String Method;
    Core::JSON::Variant Params;
};

static bool ExtractContextFields(const ResolveRequestData& req,
                                 uint32_t& requestId,
                                 uint32_t& connectionId,
                                 string& appId)
{
    // Prefer nested context if present.
    const bool hasContext =
        req.Context.RequestId.IsSet() || req.Context.ConnectionId.IsSet() || req.Context.AppId.IsSet();

    if (hasContext) {
        if (!req.Context.RequestId.IsSet() || !req.Context.ConnectionId.IsSet() || !req.Context.AppId.IsSet()) {
            return false;
        }
        requestId = req.Context.RequestId.Value();
        connectionId = req.Context.ConnectionId.Value();
        appId = req.Context.AppId.Value();
        return !appId.empty();
    }

    // Fallback to top-level fields.
    if (!req.RequestId.IsSet() || !req.ConnectionId.IsSet() || !req.AppId.IsSet()) {
        return false;
    }
    requestId = req.RequestId.Value();
    connectionId = req.ConnectionId.Value();
    appId = req.AppId.Value();
    return !appId.empty();
}

static string NormalizeParamsToJsonText(const ResolveRequestData& req)
{
    // Missing/null params => treat as {} (params are optional in JSON-RPC).
    if (!req.Params.IsSet() || req.Params.IsNull()) {
        return _T("{}");
    }

    // If params is a STRING, interpret it as already JSON text (or empty => {}).
    if (req.Params.Content() == Core::JSON::Variant::type::STRING) {
        string raw = req.Params.Value(); // Value() is raw (no surrounding quotes)
        if (raw.empty()) {
            return _T("{}");
        }
        return raw;
    }

    // Otherwise (object/array/number/bool) the Variant already stores the JSON fragment text
    // in its underlying JSON::String base. Do NOT call Variant::ToString() as that symbol
    // is not available in some Thunder SDK builds (leads to undefined reference at link time).
    const string out = req.Params.Value();
    if (out.empty()) {
        return _T("{}");
    }
    return out;
}

} // namespace detail

PUSH_WARNING(DISABLE_WARNING_UNUSED_FUNCTIONS)

// PUBLIC_INTERFACE
inline void Register(PluginHost::JSONRPC& module, IAppGatewayResolver* impl)
{
    /** Register the minimal JSON-RPC method bindings for AppGatewayResolver ("resolve"). */
    ASSERT(impl != nullptr);

    module.RegisterVersion(_T("JAppGatewayResolver"), Version::Major, Version::Minor, Version::Patch);

    // Register "resolve" as a raw InvokeFunction so we can:
    //  - detect malformed JSON (FromString error)
    //  - support two request shapes used across L0 tests
    //  - normalize params consistently ("" => "{}", object => JSON string)
    module.Register(_T("resolve"),
        [impl](const Core::JSONRPC::Context& /*ctx*/,
               const string& /*designator*/,
               const string& parameters,
               string& response) -> uint32_t {
            detail::ResolveRequestData req;
            Core::OptionalType<Core::JSON::Error> error;

            if (req.FromString(parameters, error) == false || error.IsSet() == true) {
                response.clear();
                return Core::ERROR_BAD_REQUEST;
            }

            // Validate required fields.
            if (!req.Origin.IsSet() || req.Origin.Value().empty()) {
                response.clear();
                return Core::ERROR_BAD_REQUEST;
            }
            if (!req.Method.IsSet() || req.Method.Value().empty()) {
                response.clear();
                return Core::ERROR_BAD_REQUEST;
            }

            uint32_t requestId = 0;
            uint32_t connectionId = 0;
            string appId;

            if (!detail::ExtractContextFields(req, requestId, connectionId, appId)) {
                response.clear();
                return Core::ERROR_BAD_REQUEST;
            }

            const string paramsJson = detail::NormalizeParamsToJsonText(req);

            GatewayContext gw;
            gw.requestId = requestId;
            gw.connectionId = connectionId;
            gw.appId = appId;

            string result;
            const uint32_t rc = impl->Resolve(gw, req.Origin.Value(), req.Method.Value(), paramsJson, result);

            response = result;
            return rc;
        });
}

// PUBLIC_INTERFACE
inline void Unregister(PluginHost::JSONRPC& module)
{
    /** Unregister the JSON-RPC method bindings for AppGatewayResolver ("resolve"). */
    module.Unregister(_T("resolve"));
}

POP_WARNING()

} // namespace JAppGatewayResolver

} // namespace Exchange
} // namespace WPEFramework
