#pragma once

// Placeholder for generated JsonData_AppGatewayResolver.h.
// In a full Thunder/WPEFramework build this file is generated by JsonGenerator.
// For L0 testing and local plugin builds, the AppGateway plugin only requires
// that this header exists and is includable.
