// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: permission_service.proto

#include "permission_service.pb.h"
#include "permission_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ottx {
namespace permission {

static const char* AppPermissionsService_method_names[] = {
  "/ottx.permission.AppPermissionsService/Get",
  "/ottx.permission.AppPermissionsService/Grant",
  "/ottx.permission.AppPermissionsService/Set",
  "/ottx.permission.AppPermissionsService/Revoke",
  "/ottx.permission.AppPermissionsService/Delete",
  "/ottx.permission.AppPermissionsService/Authorize",
  "/ottx.permission.AppPermissionsService/EnumeratePermissions",
  "/ottx.permission.AppPermissionsService/GetAllForApp",
  "/ottx.permission.AppPermissionsService/GetAllAppKeys",
  "/ottx.permission.AppPermissionsService/GetThorToken",
  "/ottx.permission.AppPermissionsService/GetRegisteredPermissions",
  "/ottx.permission.AppPermissionsService/RegisterPermissions",
  "/ottx.permission.AppPermissionsService/DeleteRegisteredPermission",
};

std::unique_ptr< AppPermissionsService::Stub> AppPermissionsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AppPermissionsService::Stub> stub(new AppPermissionsService::Stub(channel, options));
  return stub;
}

AppPermissionsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(AppPermissionsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Grant_(AppPermissionsService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(AppPermissionsService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Revoke_(AppPermissionsService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(AppPermissionsService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Authorize_(AppPermissionsService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EnumeratePermissions_(AppPermissionsService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllForApp_(AppPermissionsService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllAppKeys_(AppPermissionsService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetThorToken_(AppPermissionsService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRegisteredPermissions_(AppPermissionsService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterPermissions_(AppPermissionsService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteRegisteredPermission_(AppPermissionsService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AppPermissionsService::Stub::Get(::grpc::ClientContext* context, const ::ottx::permission::GetRequest& request, ::ottx::permission::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GetRequest, ::ottx::permission::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void AppPermissionsService::Stub::async::Get(::grpc::ClientContext* context, const ::ottx::permission::GetRequest* request, ::ottx::permission::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GetRequest, ::ottx::permission::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Get(::grpc::ClientContext* context, const ::ottx::permission::GetRequest* request, ::ottx::permission::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetResponse>* AppPermissionsService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::ottx::permission::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GetResponse, ::ottx::permission::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetResponse>* AppPermissionsService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::ottx::permission::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::Grant(::grpc::ClientContext* context, const ::ottx::permission::GrantRequest& request, ::ottx::permission::GrantResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GrantRequest, ::ottx::permission::GrantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Grant_, context, request, response);
}

void AppPermissionsService::Stub::async::Grant(::grpc::ClientContext* context, const ::ottx::permission::GrantRequest* request, ::ottx::permission::GrantResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GrantRequest, ::ottx::permission::GrantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Grant_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Grant(::grpc::ClientContext* context, const ::ottx::permission::GrantRequest* request, ::ottx::permission::GrantResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Grant_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GrantResponse>* AppPermissionsService::Stub::PrepareAsyncGrantRaw(::grpc::ClientContext* context, const ::ottx::permission::GrantRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GrantResponse, ::ottx::permission::GrantRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Grant_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GrantResponse>* AppPermissionsService::Stub::AsyncGrantRaw(::grpc::ClientContext* context, const ::ottx::permission::GrantRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGrantRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::Set(::grpc::ClientContext* context, const ::ottx::permission::SetRequest& request, ::ottx::permission::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::SetRequest, ::ottx::permission::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void AppPermissionsService::Stub::async::Set(::grpc::ClientContext* context, const ::ottx::permission::SetRequest* request, ::ottx::permission::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::SetRequest, ::ottx::permission::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Set(::grpc::ClientContext* context, const ::ottx::permission::SetRequest* request, ::ottx::permission::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::SetResponse>* AppPermissionsService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::ottx::permission::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::SetResponse, ::ottx::permission::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::SetResponse>* AppPermissionsService::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::ottx::permission::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::Revoke(::grpc::ClientContext* context, const ::ottx::permission::RevokeRequest& request, ::ottx::permission::RevokeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::RevokeRequest, ::ottx::permission::RevokeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Revoke_, context, request, response);
}

void AppPermissionsService::Stub::async::Revoke(::grpc::ClientContext* context, const ::ottx::permission::RevokeRequest* request, ::ottx::permission::RevokeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::RevokeRequest, ::ottx::permission::RevokeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Revoke_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Revoke(::grpc::ClientContext* context, const ::ottx::permission::RevokeRequest* request, ::ottx::permission::RevokeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Revoke_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::RevokeResponse>* AppPermissionsService::Stub::PrepareAsyncRevokeRaw(::grpc::ClientContext* context, const ::ottx::permission::RevokeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::RevokeResponse, ::ottx::permission::RevokeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Revoke_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::RevokeResponse>* AppPermissionsService::Stub::AsyncRevokeRaw(::grpc::ClientContext* context, const ::ottx::permission::RevokeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRevokeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::Delete(::grpc::ClientContext* context, const ::ottx::permission::DeleteRequest& request, ::ottx::permission::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::DeleteRequest, ::ottx::permission::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void AppPermissionsService::Stub::async::Delete(::grpc::ClientContext* context, const ::ottx::permission::DeleteRequest* request, ::ottx::permission::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::DeleteRequest, ::ottx::permission::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Delete(::grpc::ClientContext* context, const ::ottx::permission::DeleteRequest* request, ::ottx::permission::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::DeleteResponse>* AppPermissionsService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::ottx::permission::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::DeleteResponse, ::ottx::permission::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::DeleteResponse>* AppPermissionsService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::ottx::permission::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::Authorize(::grpc::ClientContext* context, const ::ottx::permission::AuthorizeRequest& request, ::ottx::permission::AuthorizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::AuthorizeRequest, ::ottx::permission::AuthorizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Authorize_, context, request, response);
}

void AppPermissionsService::Stub::async::Authorize(::grpc::ClientContext* context, const ::ottx::permission::AuthorizeRequest* request, ::ottx::permission::AuthorizeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::AuthorizeRequest, ::ottx::permission::AuthorizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Authorize_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::Authorize(::grpc::ClientContext* context, const ::ottx::permission::AuthorizeRequest* request, ::ottx::permission::AuthorizeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Authorize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::AuthorizeResponse>* AppPermissionsService::Stub::PrepareAsyncAuthorizeRaw(::grpc::ClientContext* context, const ::ottx::permission::AuthorizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::AuthorizeResponse, ::ottx::permission::AuthorizeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Authorize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::AuthorizeResponse>* AppPermissionsService::Stub::AsyncAuthorizeRaw(::grpc::ClientContext* context, const ::ottx::permission::AuthorizeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthorizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::ottx::permission::EnumeratePermissionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnumeratePermissions_, context, request, response);
}

void AppPermissionsService::Stub::async::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnumeratePermissions_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::EnumeratePermissions(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnumeratePermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* AppPermissionsService::Stub::PrepareAsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::EnumeratePermissionsResponse, ::ottx::permission::EnumeratePermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnumeratePermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::EnumeratePermissionsResponse>* AppPermissionsService::Stub::AsyncEnumeratePermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::EnumeratePermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnumeratePermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::GetAllForApp(::grpc::ClientContext* context, const ::ottx::permission::GetAllForAppRequest& request, ::ottx::permission::GetAllForAppResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GetAllForAppRequest, ::ottx::permission::GetAllForAppResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllForApp_, context, request, response);
}

void AppPermissionsService::Stub::async::GetAllForApp(::grpc::ClientContext* context, const ::ottx::permission::GetAllForAppRequest* request, ::ottx::permission::GetAllForAppResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GetAllForAppRequest, ::ottx::permission::GetAllForAppResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllForApp_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::GetAllForApp(::grpc::ClientContext* context, const ::ottx::permission::GetAllForAppRequest* request, ::ottx::permission::GetAllForAppResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllForApp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetAllForAppResponse>* AppPermissionsService::Stub::PrepareAsyncGetAllForAppRaw(::grpc::ClientContext* context, const ::ottx::permission::GetAllForAppRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GetAllForAppResponse, ::ottx::permission::GetAllForAppRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllForApp_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetAllForAppResponse>* AppPermissionsService::Stub::AsyncGetAllForAppRaw(::grpc::ClientContext* context, const ::ottx::permission::GetAllForAppRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllForAppRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::GetAllAppKeys(::grpc::ClientContext* context, const ::ottx::permission::GetAllAppKeysRequest& request, ::ottx::permission::GetAllAppKeysResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GetAllAppKeysRequest, ::ottx::permission::GetAllAppKeysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllAppKeys_, context, request, response);
}

void AppPermissionsService::Stub::async::GetAllAppKeys(::grpc::ClientContext* context, const ::ottx::permission::GetAllAppKeysRequest* request, ::ottx::permission::GetAllAppKeysResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GetAllAppKeysRequest, ::ottx::permission::GetAllAppKeysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllAppKeys_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::GetAllAppKeys(::grpc::ClientContext* context, const ::ottx::permission::GetAllAppKeysRequest* request, ::ottx::permission::GetAllAppKeysResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllAppKeys_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetAllAppKeysResponse>* AppPermissionsService::Stub::PrepareAsyncGetAllAppKeysRaw(::grpc::ClientContext* context, const ::ottx::permission::GetAllAppKeysRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GetAllAppKeysResponse, ::ottx::permission::GetAllAppKeysRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllAppKeys_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetAllAppKeysResponse>* AppPermissionsService::Stub::AsyncGetAllAppKeysRaw(::grpc::ClientContext* context, const ::ottx::permission::GetAllAppKeysRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllAppKeysRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::GetThorToken(::grpc::ClientContext* context, const ::ottx::permission::GetThorTokenRequest& request, ::ottx::permission::GetThorTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GetThorTokenRequest, ::ottx::permission::GetThorTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetThorToken_, context, request, response);
}

void AppPermissionsService::Stub::async::GetThorToken(::grpc::ClientContext* context, const ::ottx::permission::GetThorTokenRequest* request, ::ottx::permission::GetThorTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GetThorTokenRequest, ::ottx::permission::GetThorTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThorToken_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::GetThorToken(::grpc::ClientContext* context, const ::ottx::permission::GetThorTokenRequest* request, ::ottx::permission::GetThorTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetThorToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetThorTokenResponse>* AppPermissionsService::Stub::PrepareAsyncGetThorTokenRaw(::grpc::ClientContext* context, const ::ottx::permission::GetThorTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GetThorTokenResponse, ::ottx::permission::GetThorTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetThorToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetThorTokenResponse>* AppPermissionsService::Stub::AsyncGetThorTokenRaw(::grpc::ClientContext* context, const ::ottx::permission::GetThorTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetThorTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::GetRegisteredPermissions(::grpc::ClientContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest& request, ::ottx::permission::GetRegisteredPermissionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::GetRegisteredPermissionsRequest, ::ottx::permission::GetRegisteredPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRegisteredPermissions_, context, request, response);
}

void AppPermissionsService::Stub::async::GetRegisteredPermissions(::grpc::ClientContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest* request, ::ottx::permission::GetRegisteredPermissionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::GetRegisteredPermissionsRequest, ::ottx::permission::GetRegisteredPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegisteredPermissions_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::GetRegisteredPermissions(::grpc::ClientContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest* request, ::ottx::permission::GetRegisteredPermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRegisteredPermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetRegisteredPermissionsResponse>* AppPermissionsService::Stub::PrepareAsyncGetRegisteredPermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::GetRegisteredPermissionsResponse, ::ottx::permission::GetRegisteredPermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRegisteredPermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::GetRegisteredPermissionsResponse>* AppPermissionsService::Stub::AsyncGetRegisteredPermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRegisteredPermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::RegisterPermissions(::grpc::ClientContext* context, const ::ottx::permission::RegisterPermissionsRequest& request, ::ottx::permission::RegisterPermissionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::RegisterPermissionsRequest, ::ottx::permission::RegisterPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterPermissions_, context, request, response);
}

void AppPermissionsService::Stub::async::RegisterPermissions(::grpc::ClientContext* context, const ::ottx::permission::RegisterPermissionsRequest* request, ::ottx::permission::RegisterPermissionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::RegisterPermissionsRequest, ::ottx::permission::RegisterPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterPermissions_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::RegisterPermissions(::grpc::ClientContext* context, const ::ottx::permission::RegisterPermissionsRequest* request, ::ottx::permission::RegisterPermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterPermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::RegisterPermissionsResponse>* AppPermissionsService::Stub::PrepareAsyncRegisterPermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::RegisterPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::RegisterPermissionsResponse, ::ottx::permission::RegisterPermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterPermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::RegisterPermissionsResponse>* AppPermissionsService::Stub::AsyncRegisterPermissionsRaw(::grpc::ClientContext* context, const ::ottx::permission::RegisterPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterPermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AppPermissionsService::Stub::DeleteRegisteredPermission(::grpc::ClientContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest& request, ::ottx::permission::DeleteRegisteredPermissionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::permission::DeleteRegisteredPermissionRequest, ::ottx::permission::DeleteRegisteredPermissionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteRegisteredPermission_, context, request, response);
}

void AppPermissionsService::Stub::async::DeleteRegisteredPermission(::grpc::ClientContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest* request, ::ottx::permission::DeleteRegisteredPermissionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::permission::DeleteRegisteredPermissionRequest, ::ottx::permission::DeleteRegisteredPermissionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteRegisteredPermission_, context, request, response, std::move(f));
}

void AppPermissionsService::Stub::async::DeleteRegisteredPermission(::grpc::ClientContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest* request, ::ottx::permission::DeleteRegisteredPermissionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteRegisteredPermission_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::DeleteRegisteredPermissionResponse>* AppPermissionsService::Stub::PrepareAsyncDeleteRegisteredPermissionRaw(::grpc::ClientContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::permission::DeleteRegisteredPermissionResponse, ::ottx::permission::DeleteRegisteredPermissionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteRegisteredPermission_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::permission::DeleteRegisteredPermissionResponse>* AppPermissionsService::Stub::AsyncDeleteRegisteredPermissionRaw(::grpc::ClientContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRegisteredPermissionRaw(context, request, cq);
  result->StartCall();
  return result;
}

AppPermissionsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GetRequest, ::ottx::permission::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GetRequest* req,
             ::ottx::permission::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GrantRequest, ::ottx::permission::GrantResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GrantRequest* req,
             ::ottx::permission::GrantResponse* resp) {
               return service->Grant(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::SetRequest, ::ottx::permission::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::SetRequest* req,
             ::ottx::permission::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::RevokeRequest, ::ottx::permission::RevokeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::RevokeRequest* req,
             ::ottx::permission::RevokeResponse* resp) {
               return service->Revoke(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::DeleteRequest, ::ottx::permission::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::DeleteRequest* req,
             ::ottx::permission::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::AuthorizeRequest, ::ottx::permission::AuthorizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::AuthorizeRequest* req,
             ::ottx::permission::AuthorizeResponse* resp) {
               return service->Authorize(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::EnumeratePermissionsRequest, ::ottx::permission::EnumeratePermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::EnumeratePermissionsRequest* req,
             ::ottx::permission::EnumeratePermissionsResponse* resp) {
               return service->EnumeratePermissions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GetAllForAppRequest, ::ottx::permission::GetAllForAppResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GetAllForAppRequest* req,
             ::ottx::permission::GetAllForAppResponse* resp) {
               return service->GetAllForApp(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GetAllAppKeysRequest, ::ottx::permission::GetAllAppKeysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GetAllAppKeysRequest* req,
             ::ottx::permission::GetAllAppKeysResponse* resp) {
               return service->GetAllAppKeys(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GetThorTokenRequest, ::ottx::permission::GetThorTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GetThorTokenRequest* req,
             ::ottx::permission::GetThorTokenResponse* resp) {
               return service->GetThorToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::GetRegisteredPermissionsRequest, ::ottx::permission::GetRegisteredPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::GetRegisteredPermissionsRequest* req,
             ::ottx::permission::GetRegisteredPermissionsResponse* resp) {
               return service->GetRegisteredPermissions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::RegisterPermissionsRequest, ::ottx::permission::RegisterPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::RegisterPermissionsRequest* req,
             ::ottx::permission::RegisterPermissionsResponse* resp) {
               return service->RegisterPermissions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppPermissionsService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppPermissionsService::Service, ::ottx::permission::DeleteRegisteredPermissionRequest, ::ottx::permission::DeleteRegisteredPermissionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppPermissionsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::permission::DeleteRegisteredPermissionRequest* req,
             ::ottx::permission::DeleteRegisteredPermissionResponse* resp) {
               return service->DeleteRegisteredPermission(ctx, req, resp);
             }, this)));
}

AppPermissionsService::Service::~Service() {
}

::grpc::Status AppPermissionsService::Service::Get(::grpc::ServerContext* context, const ::ottx::permission::GetRequest* request, ::ottx::permission::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::Grant(::grpc::ServerContext* context, const ::ottx::permission::GrantRequest* request, ::ottx::permission::GrantResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::Set(::grpc::ServerContext* context, const ::ottx::permission::SetRequest* request, ::ottx::permission::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::Revoke(::grpc::ServerContext* context, const ::ottx::permission::RevokeRequest* request, ::ottx::permission::RevokeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::Delete(::grpc::ServerContext* context, const ::ottx::permission::DeleteRequest* request, ::ottx::permission::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::Authorize(::grpc::ServerContext* context, const ::ottx::permission::AuthorizeRequest* request, ::ottx::permission::AuthorizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::EnumeratePermissions(::grpc::ServerContext* context, const ::ottx::permission::EnumeratePermissionsRequest* request, ::ottx::permission::EnumeratePermissionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::GetAllForApp(::grpc::ServerContext* context, const ::ottx::permission::GetAllForAppRequest* request, ::ottx::permission::GetAllForAppResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::GetAllAppKeys(::grpc::ServerContext* context, const ::ottx::permission::GetAllAppKeysRequest* request, ::ottx::permission::GetAllAppKeysResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::GetThorToken(::grpc::ServerContext* context, const ::ottx::permission::GetThorTokenRequest* request, ::ottx::permission::GetThorTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::GetRegisteredPermissions(::grpc::ServerContext* context, const ::ottx::permission::GetRegisteredPermissionsRequest* request, ::ottx::permission::GetRegisteredPermissionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::RegisterPermissions(::grpc::ServerContext* context, const ::ottx::permission::RegisterPermissionsRequest* request, ::ottx::permission::RegisterPermissionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AppPermissionsService::Service::DeleteRegisteredPermission(::grpc::ServerContext* context, const ::ottx::permission::DeleteRegisteredPermissionRequest* request, ::ottx::permission::DeleteRegisteredPermissionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ottx
}  // namespace permission

