// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ott_token.proto
#ifndef GRPC_ott_5ftoken_2eproto__INCLUDED
#define GRPC_ott_5ftoken_2eproto__INCLUDED

#include "ott_token.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ottx {
namespace otttoken {

// OttToken handles Silent Token retrival per Partner
class OttTokenService final {
 public:
  static constexpr char const* service_full_name() {
    return "ottx.otttoken.OttTokenService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // AuthToken request to retrieve the token per partner.
    virtual ::grpc::Status AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::ottx::otttoken::AuthTokenResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>> AsyncAuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>>(AsyncAuthTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>> PrepareAsyncAuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>>(PrepareAsyncAuthTokenRaw(context, request, cq));
    }
    virtual ::grpc::Status PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::ottx::otttoken::PlatformTokenResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>> AsyncPlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>>(AsyncPlatformTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>> PrepareAsyncPlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>>(PrepareAsyncPlatformTokenRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // AuthToken request to retrieve the token per partner.
      virtual void AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>* AsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::AuthTokenResponse>* PrepareAsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>* AsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ottx::otttoken::PlatformTokenResponse>* PrepareAsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::ottx::otttoken::AuthTokenResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>> AsyncAuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>>(AsyncAuthTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>> PrepareAsyncAuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>>(PrepareAsyncAuthTokenRaw(context, request, cq));
    }
    ::grpc::Status PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::ottx::otttoken::PlatformTokenResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>> AsyncPlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>>(AsyncPlatformTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>> PrepareAsyncPlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>>(PrepareAsyncPlatformTokenRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, std::function<void(::grpc::Status)>) override;
      void AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, std::function<void(::grpc::Status)>) override;
      void PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>* AsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>* PrepareAsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>* AsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>* PrepareAsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AuthToken_;
    const ::grpc::internal::RpcMethod rpcmethod_PlatformToken_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // AuthToken request to retrieve the token per partner.
    virtual ::grpc::Status AuthToken(::grpc::ServerContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response);
    virtual ::grpc::Status PlatformToken(::grpc::ServerContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AuthToken() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthToken(::grpc::ServerContext* context, ::ottx::otttoken::AuthTokenRequest* request, ::grpc::ServerAsyncResponseWriter< ::ottx::otttoken::AuthTokenResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PlatformToken() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlatformToken(::grpc::ServerContext* context, ::ottx::otttoken::PlatformTokenRequest* request, ::grpc::ServerAsyncResponseWriter< ::ottx::otttoken::PlatformTokenResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AuthToken<WithAsyncMethod_PlatformToken<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AuthToken() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response) { return this->AuthToken(context, request, response); }));}
    void SetMessageAllocatorFor_AuthToken(
        ::grpc::MessageAllocator< ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthToken(
      ::grpc::CallbackServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PlatformToken() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response) { return this->PlatformToken(context, request, response); }));}
    void SetMessageAllocatorFor_PlatformToken(
        ::grpc::MessageAllocator< ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlatformToken(
      ::grpc::CallbackServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AuthToken<WithCallbackMethod_PlatformToken<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AuthToken() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PlatformToken() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AuthToken() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PlatformToken() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlatformToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AuthToken() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AuthToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PlatformToken() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PlatformToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlatformToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AuthToken() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse>* streamer) {
                       return this->StreamedAuthToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AuthToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::AuthTokenRequest* /*request*/, ::ottx::otttoken::AuthTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ottx::otttoken::AuthTokenRequest,::ottx::otttoken::AuthTokenResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PlatformToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PlatformToken() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse>* streamer) {
                       return this->StreamedPlatformToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PlatformToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PlatformToken(::grpc::ServerContext* /*context*/, const ::ottx::otttoken::PlatformTokenRequest* /*request*/, ::ottx::otttoken::PlatformTokenResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlatformToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ottx::otttoken::PlatformTokenRequest,::ottx::otttoken::PlatformTokenResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AuthToken<WithStreamedUnaryMethod_PlatformToken<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AuthToken<WithStreamedUnaryMethod_PlatformToken<Service > > StreamedService;
};

}  // namespace otttoken
}  // namespace ottx


#endif  // GRPC_ott_5ftoken_2eproto__INCLUDED
