// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ott_token.proto

#include "ott_token.pb.h"
#include "ott_token.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ottx {
namespace otttoken {

static const char* OttTokenService_method_names[] = {
  "/ottx.otttoken.OttTokenService/AuthToken",
  "/ottx.otttoken.OttTokenService/PlatformToken",
};

std::unique_ptr< OttTokenService::Stub> OttTokenService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OttTokenService::Stub> stub(new OttTokenService::Stub(channel, options));
  return stub;
}

OttTokenService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AuthToken_(OttTokenService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PlatformToken_(OttTokenService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OttTokenService::Stub::AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::ottx::otttoken::AuthTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AuthToken_, context, request, response);
}

void OttTokenService::Stub::async::AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthToken_, context, request, response, std::move(f));
}

void OttTokenService::Stub::async::AuthToken(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>* OttTokenService::Stub::PrepareAsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::otttoken::AuthTokenResponse, ::ottx::otttoken::AuthTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AuthToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::otttoken::AuthTokenResponse>* OttTokenService::Stub::AsyncAuthTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::AuthTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OttTokenService::Stub::PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::ottx::otttoken::PlatformTokenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PlatformToken_, context, request, response);
}

void OttTokenService::Stub::async::PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlatformToken_, context, request, response, std::move(f));
}

void OttTokenService::Stub::async::PlatformToken(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PlatformToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>* OttTokenService::Stub::PrepareAsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ottx::otttoken::PlatformTokenResponse, ::ottx::otttoken::PlatformTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PlatformToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ottx::otttoken::PlatformTokenResponse>* OttTokenService::Stub::AsyncPlatformTokenRaw(::grpc::ClientContext* context, const ::ottx::otttoken::PlatformTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPlatformTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

OttTokenService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OttTokenService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OttTokenService::Service, ::ottx::otttoken::AuthTokenRequest, ::ottx::otttoken::AuthTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OttTokenService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::otttoken::AuthTokenRequest* req,
             ::ottx::otttoken::AuthTokenResponse* resp) {
               return service->AuthToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OttTokenService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OttTokenService::Service, ::ottx::otttoken::PlatformTokenRequest, ::ottx::otttoken::PlatformTokenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OttTokenService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ottx::otttoken::PlatformTokenRequest* req,
             ::ottx::otttoken::PlatformTokenResponse* resp) {
               return service->PlatformToken(ctx, req, resp);
             }, this)));
}

OttTokenService::Service::~Service() {
}

::grpc::Status OttTokenService::Service::AuthToken(::grpc::ServerContext* context, const ::ottx::otttoken::AuthTokenRequest* request, ::ottx::otttoken::AuthTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OttTokenService::Service::PlatformToken(::grpc::ServerContext* context, const ::ottx::otttoken::PlatformTokenRequest* request, ::ottx::otttoken::PlatformTokenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ottx
}  // namespace otttoken

