// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ott_token.proto

#include "ott_token.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace ottx {
namespace otttoken {
constexpr AuthTokenRequest::AuthTokenRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : partner_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , app_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , xsct_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sat_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct AuthTokenRequestDefaultTypeInternal {
  constexpr AuthTokenRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AuthTokenRequestDefaultTypeInternal() {}
  union {
    AuthTokenRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AuthTokenRequestDefaultTypeInternal _AuthTokenRequest_default_instance_;
constexpr AuthTokenResponse::AuthTokenResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : access_token_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , token_type_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , scope_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , expires_in_(0){}
struct AuthTokenResponseDefaultTypeInternal {
  constexpr AuthTokenResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~AuthTokenResponseDefaultTypeInternal() {}
  union {
    AuthTokenResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT AuthTokenResponseDefaultTypeInternal _AuthTokenResponse_default_instance_;
constexpr PlatformTokenRequest::PlatformTokenRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : xact_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sat_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , app_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct PlatformTokenRequestDefaultTypeInternal {
  constexpr PlatformTokenRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PlatformTokenRequestDefaultTypeInternal() {}
  union {
    PlatformTokenRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PlatformTokenRequestDefaultTypeInternal _PlatformTokenRequest_default_instance_;
constexpr PlatformTokenResponse::PlatformTokenResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : platform_token_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , token_type_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , scope_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , expires_in_(0){}
struct PlatformTokenResponseDefaultTypeInternal {
  constexpr PlatformTokenResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PlatformTokenResponseDefaultTypeInternal() {}
  union {
    PlatformTokenResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PlatformTokenResponseDefaultTypeInternal _PlatformTokenResponse_default_instance_;
}  // namespace otttoken
}  // namespace ottx
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ott_5ftoken_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ott_5ftoken_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ott_5ftoken_2eproto = nullptr;

const uint32_t TableStruct_ott_5ftoken_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenRequest, partner_id_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenRequest, app_id_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenRequest, xsct_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenRequest, sat_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenResponse, access_token_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenResponse, token_type_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenResponse, scope_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::AuthTokenResponse, expires_in_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenRequest, xact_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenRequest, sat_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenRequest, app_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenResponse, platform_token_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenResponse, token_type_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenResponse, expires_in_),
  PROTOBUF_FIELD_OFFSET(::ottx::otttoken::PlatformTokenResponse, scope_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ottx::otttoken::AuthTokenRequest)},
  { 10, -1, -1, sizeof(::ottx::otttoken::AuthTokenResponse)},
  { 20, -1, -1, sizeof(::ottx::otttoken::PlatformTokenRequest)},
  { 29, -1, -1, sizeof(::ottx::otttoken::PlatformTokenResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ottx::otttoken::_AuthTokenRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ottx::otttoken::_AuthTokenResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ottx::otttoken::_PlatformTokenRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ottx::otttoken::_PlatformTokenResponse_default_instance_),
};

const char descriptor_table_protodef_ott_5ftoken_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017ott_token.proto\022\rottx.otttoken\"Q\n\020Auth"
  "TokenRequest\022\022\n\npartner_id\030\001 \001(\t\022\016\n\006app_"
  "id\030\002 \001(\t\022\014\n\004xsct\030\003 \001(\t\022\013\n\003sat\030\004 \001(\t\"`\n\021A"
  "uthTokenResponse\022\024\n\014access_token\030\001 \001(\t\022\022"
  "\n\ntoken_type\030\002 \001(\t\022\r\n\005scope\030\003 \001(\t\022\022\n\nexp"
  "ires_in\030\004 \001(\005\"A\n\024PlatformTokenRequest\022\014\n"
  "\004xact\030\001 \001(\t\022\013\n\003sat\030\002 \001(\t\022\016\n\006app_id\030\003 \001(\t"
  "\"f\n\025PlatformTokenResponse\022\026\n\016platform_to"
  "ken\030\001 \001(\t\022\022\n\ntoken_type\030\002 \001(\t\022\022\n\nexpires"
  "_in\030\003 \001(\005\022\r\n\005scope\030\004 \001(\t2\275\001\n\017OttTokenSer"
  "vice\022N\n\tAuthToken\022\037.ottx.otttoken.AuthTo"
  "kenRequest\032 .ottx.otttoken.AuthTokenResp"
  "onse\022Z\n\rPlatformToken\022#.ottx.otttoken.Pl"
  "atformTokenRequest\032$.ottx.otttoken.Platf"
  "ormTokenResponseBd\n\032code.comcast.ottx.ot"
  "ttokenP\001ZDgithub.com/comcast-ottx-racers"
  "/ottx-protobuf/api/ott_token;ott_tokenb\006"
  "proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ott_5ftoken_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ott_5ftoken_2eproto = {
  false, false, 686, descriptor_table_protodef_ott_5ftoken_2eproto, "ott_token.proto", 
  &descriptor_table_ott_5ftoken_2eproto_once, nullptr, 0, 4,
  schemas, file_default_instances, TableStruct_ott_5ftoken_2eproto::offsets,
  file_level_metadata_ott_5ftoken_2eproto, file_level_enum_descriptors_ott_5ftoken_2eproto, file_level_service_descriptors_ott_5ftoken_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ott_5ftoken_2eproto_getter() {
  return &descriptor_table_ott_5ftoken_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ott_5ftoken_2eproto(&descriptor_table_ott_5ftoken_2eproto);
namespace ottx {
namespace otttoken {

// ===================================================================

class AuthTokenRequest::_Internal {
 public:
};

AuthTokenRequest::AuthTokenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ottx.otttoken.AuthTokenRequest)
}
AuthTokenRequest::AuthTokenRequest(const AuthTokenRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  partner_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    partner_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_partner_id().empty()) {
    partner_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_partner_id(), 
      GetArenaForAllocation());
  }
  app_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app_id().empty()) {
    app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_app_id(), 
      GetArenaForAllocation());
  }
  xsct_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    xsct_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_xsct().empty()) {
    xsct_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_xsct(), 
      GetArenaForAllocation());
  }
  sat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sat().empty()) {
    sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sat(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ottx.otttoken.AuthTokenRequest)
}

inline void AuthTokenRequest::SharedCtor() {
partner_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  partner_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
app_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
xsct_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  xsct_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
sat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AuthTokenRequest::~AuthTokenRequest() {
  // @@protoc_insertion_point(destructor:ottx.otttoken.AuthTokenRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void AuthTokenRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  partner_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  app_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  xsct_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sat_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AuthTokenRequest::ArenaDtor(void* object) {
  AuthTokenRequest* _this = reinterpret_cast< AuthTokenRequest* >(object);
  (void)_this;
}
void AuthTokenRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AuthTokenRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AuthTokenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.otttoken.AuthTokenRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  partner_id_.ClearToEmpty();
  app_id_.ClearToEmpty();
  xsct_.ClearToEmpty();
  sat_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AuthTokenRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string partner_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_partner_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenRequest.partner_id"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string app_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_app_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenRequest.app_id"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string xsct = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_xsct();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenRequest.xsct"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string sat = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_sat();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenRequest.sat"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AuthTokenRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.otttoken.AuthTokenRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string partner_id = 1;
  if (!this->_internal_partner_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_partner_id().data(), static_cast<int>(this->_internal_partner_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenRequest.partner_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_partner_id(), target);
  }

  // string app_id = 2;
  if (!this->_internal_app_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_id().data(), static_cast<int>(this->_internal_app_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenRequest.app_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_app_id(), target);
  }

  // string xsct = 3;
  if (!this->_internal_xsct().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_xsct().data(), static_cast<int>(this->_internal_xsct().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenRequest.xsct");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_xsct(), target);
  }

  // string sat = 4;
  if (!this->_internal_sat().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sat().data(), static_cast<int>(this->_internal_sat().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenRequest.sat");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_sat(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.otttoken.AuthTokenRequest)
  return target;
}

size_t AuthTokenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.otttoken.AuthTokenRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string partner_id = 1;
  if (!this->_internal_partner_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_partner_id());
  }

  // string app_id = 2;
  if (!this->_internal_app_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_id());
  }

  // string xsct = 3;
  if (!this->_internal_xsct().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_xsct());
  }

  // string sat = 4;
  if (!this->_internal_sat().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sat());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AuthTokenRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    AuthTokenRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AuthTokenRequest::GetClassData() const { return &_class_data_; }

void AuthTokenRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<AuthTokenRequest *>(to)->MergeFrom(
      static_cast<const AuthTokenRequest &>(from));
}


void AuthTokenRequest::MergeFrom(const AuthTokenRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ottx.otttoken.AuthTokenRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_partner_id().empty()) {
    _internal_set_partner_id(from._internal_partner_id());
  }
  if (!from._internal_app_id().empty()) {
    _internal_set_app_id(from._internal_app_id());
  }
  if (!from._internal_xsct().empty()) {
    _internal_set_xsct(from._internal_xsct());
  }
  if (!from._internal_sat().empty()) {
    _internal_set_sat(from._internal_sat());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AuthTokenRequest::CopyFrom(const AuthTokenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.otttoken.AuthTokenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthTokenRequest::IsInitialized() const {
  return true;
}

void AuthTokenRequest::InternalSwap(AuthTokenRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &partner_id_, lhs_arena,
      &other->partner_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &app_id_, lhs_arena,
      &other->app_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &xsct_, lhs_arena,
      &other->xsct_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sat_, lhs_arena,
      &other->sat_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AuthTokenRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ott_5ftoken_2eproto_getter, &descriptor_table_ott_5ftoken_2eproto_once,
      file_level_metadata_ott_5ftoken_2eproto[0]);
}

// ===================================================================

class AuthTokenResponse::_Internal {
 public:
};

AuthTokenResponse::AuthTokenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ottx.otttoken.AuthTokenResponse)
}
AuthTokenResponse::AuthTokenResponse(const AuthTokenResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  access_token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    access_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_access_token().empty()) {
    access_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_access_token(), 
      GetArenaForAllocation());
  }
  token_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token_type().empty()) {
    token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_token_type(), 
      GetArenaForAllocation());
  }
  scope_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scope().empty()) {
    scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_scope(), 
      GetArenaForAllocation());
  }
  expires_in_ = from.expires_in_;
  // @@protoc_insertion_point(copy_constructor:ottx.otttoken.AuthTokenResponse)
}

inline void AuthTokenResponse::SharedCtor() {
access_token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  access_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
token_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
scope_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
expires_in_ = 0;
}

AuthTokenResponse::~AuthTokenResponse() {
  // @@protoc_insertion_point(destructor:ottx.otttoken.AuthTokenResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void AuthTokenResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  access_token_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  token_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  scope_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AuthTokenResponse::ArenaDtor(void* object) {
  AuthTokenResponse* _this = reinterpret_cast< AuthTokenResponse* >(object);
  (void)_this;
}
void AuthTokenResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AuthTokenResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void AuthTokenResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.otttoken.AuthTokenResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  access_token_.ClearToEmpty();
  token_type_.ClearToEmpty();
  scope_.ClearToEmpty();
  expires_in_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AuthTokenResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string access_token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_access_token();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenResponse.access_token"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string token_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_token_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenResponse.token_type"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string scope = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_scope();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.AuthTokenResponse.scope"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 expires_in = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          expires_in_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AuthTokenResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.otttoken.AuthTokenResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string access_token = 1;
  if (!this->_internal_access_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_access_token().data(), static_cast<int>(this->_internal_access_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenResponse.access_token");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_access_token(), target);
  }

  // string token_type = 2;
  if (!this->_internal_token_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token_type().data(), static_cast<int>(this->_internal_token_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenResponse.token_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_token_type(), target);
  }

  // string scope = 3;
  if (!this->_internal_scope().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scope().data(), static_cast<int>(this->_internal_scope().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.AuthTokenResponse.scope");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_scope(), target);
  }

  // int32 expires_in = 4;
  if (this->_internal_expires_in() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_expires_in(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.otttoken.AuthTokenResponse)
  return target;
}

size_t AuthTokenResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.otttoken.AuthTokenResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string access_token = 1;
  if (!this->_internal_access_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_access_token());
  }

  // string token_type = 2;
  if (!this->_internal_token_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token_type());
  }

  // string scope = 3;
  if (!this->_internal_scope().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scope());
  }

  // int32 expires_in = 4;
  if (this->_internal_expires_in() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_expires_in());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AuthTokenResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    AuthTokenResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AuthTokenResponse::GetClassData() const { return &_class_data_; }

void AuthTokenResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<AuthTokenResponse *>(to)->MergeFrom(
      static_cast<const AuthTokenResponse &>(from));
}


void AuthTokenResponse::MergeFrom(const AuthTokenResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ottx.otttoken.AuthTokenResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_access_token().empty()) {
    _internal_set_access_token(from._internal_access_token());
  }
  if (!from._internal_token_type().empty()) {
    _internal_set_token_type(from._internal_token_type());
  }
  if (!from._internal_scope().empty()) {
    _internal_set_scope(from._internal_scope());
  }
  if (from._internal_expires_in() != 0) {
    _internal_set_expires_in(from._internal_expires_in());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AuthTokenResponse::CopyFrom(const AuthTokenResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.otttoken.AuthTokenResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthTokenResponse::IsInitialized() const {
  return true;
}

void AuthTokenResponse::InternalSwap(AuthTokenResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &access_token_, lhs_arena,
      &other->access_token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &token_type_, lhs_arena,
      &other->token_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &scope_, lhs_arena,
      &other->scope_, rhs_arena
  );
  swap(expires_in_, other->expires_in_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AuthTokenResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ott_5ftoken_2eproto_getter, &descriptor_table_ott_5ftoken_2eproto_once,
      file_level_metadata_ott_5ftoken_2eproto[1]);
}

// ===================================================================

class PlatformTokenRequest::_Internal {
 public:
};

PlatformTokenRequest::PlatformTokenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ottx.otttoken.PlatformTokenRequest)
}
PlatformTokenRequest::PlatformTokenRequest(const PlatformTokenRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  xact_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    xact_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_xact().empty()) {
    xact_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_xact(), 
      GetArenaForAllocation());
  }
  sat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sat().empty()) {
    sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sat(), 
      GetArenaForAllocation());
  }
  app_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app_id().empty()) {
    app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_app_id(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ottx.otttoken.PlatformTokenRequest)
}

inline void PlatformTokenRequest::SharedCtor() {
xact_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  xact_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
sat_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
app_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PlatformTokenRequest::~PlatformTokenRequest() {
  // @@protoc_insertion_point(destructor:ottx.otttoken.PlatformTokenRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void PlatformTokenRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  xact_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sat_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  app_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PlatformTokenRequest::ArenaDtor(void* object) {
  PlatformTokenRequest* _this = reinterpret_cast< PlatformTokenRequest* >(object);
  (void)_this;
}
void PlatformTokenRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlatformTokenRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PlatformTokenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.otttoken.PlatformTokenRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  xact_.ClearToEmpty();
  sat_.ClearToEmpty();
  app_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlatformTokenRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string xact = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_xact();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenRequest.xact"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string sat = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sat();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenRequest.sat"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string app_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_app_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenRequest.app_id"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlatformTokenRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.otttoken.PlatformTokenRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string xact = 1;
  if (!this->_internal_xact().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_xact().data(), static_cast<int>(this->_internal_xact().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenRequest.xact");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_xact(), target);
  }

  // string sat = 2;
  if (!this->_internal_sat().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sat().data(), static_cast<int>(this->_internal_sat().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenRequest.sat");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sat(), target);
  }

  // string app_id = 3;
  if (!this->_internal_app_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_id().data(), static_cast<int>(this->_internal_app_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenRequest.app_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_app_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.otttoken.PlatformTokenRequest)
  return target;
}

size_t PlatformTokenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.otttoken.PlatformTokenRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string xact = 1;
  if (!this->_internal_xact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_xact());
  }

  // string sat = 2;
  if (!this->_internal_sat().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sat());
  }

  // string app_id = 3;
  if (!this->_internal_app_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlatformTokenRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PlatformTokenRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlatformTokenRequest::GetClassData() const { return &_class_data_; }

void PlatformTokenRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PlatformTokenRequest *>(to)->MergeFrom(
      static_cast<const PlatformTokenRequest &>(from));
}


void PlatformTokenRequest::MergeFrom(const PlatformTokenRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ottx.otttoken.PlatformTokenRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_xact().empty()) {
    _internal_set_xact(from._internal_xact());
  }
  if (!from._internal_sat().empty()) {
    _internal_set_sat(from._internal_sat());
  }
  if (!from._internal_app_id().empty()) {
    _internal_set_app_id(from._internal_app_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlatformTokenRequest::CopyFrom(const PlatformTokenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.otttoken.PlatformTokenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlatformTokenRequest::IsInitialized() const {
  return true;
}

void PlatformTokenRequest::InternalSwap(PlatformTokenRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &xact_, lhs_arena,
      &other->xact_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sat_, lhs_arena,
      &other->sat_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &app_id_, lhs_arena,
      &other->app_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PlatformTokenRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ott_5ftoken_2eproto_getter, &descriptor_table_ott_5ftoken_2eproto_once,
      file_level_metadata_ott_5ftoken_2eproto[2]);
}

// ===================================================================

class PlatformTokenResponse::_Internal {
 public:
};

PlatformTokenResponse::PlatformTokenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:ottx.otttoken.PlatformTokenResponse)
}
PlatformTokenResponse::PlatformTokenResponse(const PlatformTokenResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  platform_token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    platform_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_platform_token().empty()) {
    platform_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_platform_token(), 
      GetArenaForAllocation());
  }
  token_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token_type().empty()) {
    token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_token_type(), 
      GetArenaForAllocation());
  }
  scope_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_scope().empty()) {
    scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_scope(), 
      GetArenaForAllocation());
  }
  expires_in_ = from.expires_in_;
  // @@protoc_insertion_point(copy_constructor:ottx.otttoken.PlatformTokenResponse)
}

inline void PlatformTokenResponse::SharedCtor() {
platform_token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  platform_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
token_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
scope_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
expires_in_ = 0;
}

PlatformTokenResponse::~PlatformTokenResponse() {
  // @@protoc_insertion_point(destructor:ottx.otttoken.PlatformTokenResponse)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void PlatformTokenResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  platform_token_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  token_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  scope_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PlatformTokenResponse::ArenaDtor(void* object) {
  PlatformTokenResponse* _this = reinterpret_cast< PlatformTokenResponse* >(object);
  (void)_this;
}
void PlatformTokenResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlatformTokenResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PlatformTokenResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.otttoken.PlatformTokenResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  platform_token_.ClearToEmpty();
  token_type_.ClearToEmpty();
  scope_.ClearToEmpty();
  expires_in_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlatformTokenResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string platform_token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_platform_token();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenResponse.platform_token"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string token_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_token_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenResponse.token_type"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 expires_in = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          expires_in_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string scope = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_scope();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ottx.otttoken.PlatformTokenResponse.scope"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlatformTokenResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.otttoken.PlatformTokenResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string platform_token = 1;
  if (!this->_internal_platform_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_platform_token().data(), static_cast<int>(this->_internal_platform_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenResponse.platform_token");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_platform_token(), target);
  }

  // string token_type = 2;
  if (!this->_internal_token_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token_type().data(), static_cast<int>(this->_internal_token_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenResponse.token_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_token_type(), target);
  }

  // int32 expires_in = 3;
  if (this->_internal_expires_in() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_expires_in(), target);
  }

  // string scope = 4;
  if (!this->_internal_scope().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_scope().data(), static_cast<int>(this->_internal_scope().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.otttoken.PlatformTokenResponse.scope");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_scope(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.otttoken.PlatformTokenResponse)
  return target;
}

size_t PlatformTokenResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.otttoken.PlatformTokenResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string platform_token = 1;
  if (!this->_internal_platform_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_platform_token());
  }

  // string token_type = 2;
  if (!this->_internal_token_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token_type());
  }

  // string scope = 4;
  if (!this->_internal_scope().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_scope());
  }

  // int32 expires_in = 3;
  if (this->_internal_expires_in() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_expires_in());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlatformTokenResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PlatformTokenResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlatformTokenResponse::GetClassData() const { return &_class_data_; }

void PlatformTokenResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PlatformTokenResponse *>(to)->MergeFrom(
      static_cast<const PlatformTokenResponse &>(from));
}


void PlatformTokenResponse::MergeFrom(const PlatformTokenResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ottx.otttoken.PlatformTokenResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_platform_token().empty()) {
    _internal_set_platform_token(from._internal_platform_token());
  }
  if (!from._internal_token_type().empty()) {
    _internal_set_token_type(from._internal_token_type());
  }
  if (!from._internal_scope().empty()) {
    _internal_set_scope(from._internal_scope());
  }
  if (from._internal_expires_in() != 0) {
    _internal_set_expires_in(from._internal_expires_in());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlatformTokenResponse::CopyFrom(const PlatformTokenResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.otttoken.PlatformTokenResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlatformTokenResponse::IsInitialized() const {
  return true;
}

void PlatformTokenResponse::InternalSwap(PlatformTokenResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &platform_token_, lhs_arena,
      &other->platform_token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &token_type_, lhs_arena,
      &other->token_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &scope_, lhs_arena,
      &other->scope_, rhs_arena
  );
  swap(expires_in_, other->expires_in_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PlatformTokenResponse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ott_5ftoken_2eproto_getter, &descriptor_table_ott_5ftoken_2eproto_once,
      file_level_metadata_ott_5ftoken_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace otttoken
}  // namespace ottx
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ottx::otttoken::AuthTokenRequest* Arena::CreateMaybeMessage< ::ottx::otttoken::AuthTokenRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::otttoken::AuthTokenRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ottx::otttoken::AuthTokenResponse* Arena::CreateMaybeMessage< ::ottx::otttoken::AuthTokenResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::otttoken::AuthTokenResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::ottx::otttoken::PlatformTokenRequest* Arena::CreateMaybeMessage< ::ottx::otttoken::PlatformTokenRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::otttoken::PlatformTokenRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ottx::otttoken::PlatformTokenResponse* Arena::CreateMaybeMessage< ::ottx::otttoken::PlatformTokenResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::otttoken::PlatformTokenResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
