// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

#include "permission_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ottx {
namespace permission {
PROTOBUF_CONSTEXPR AppKey::AppKey(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.app_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.syndication_partner_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AppKeyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppKeyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppKeyDefaultTypeInternal() {}
  union {
    AppKey _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppKeyDefaultTypeInternal _AppKey_default_instance_;
PROTOBUF_CONSTEXPR EnumeratePermissionsRequest::EnumeratePermissionsRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.permission_filters_)*/{}
  , /*decltype(_impl_.app_key_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EnumeratePermissionsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnumeratePermissionsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnumeratePermissionsRequestDefaultTypeInternal() {}
  union {
    EnumeratePermissionsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnumeratePermissionsRequestDefaultTypeInternal _EnumeratePermissionsRequest_default_instance_;
PROTOBUF_CONSTEXPR EnumeratePermissionsResponse::EnumeratePermissionsResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.permissions_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EnumeratePermissionsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnumeratePermissionsResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnumeratePermissionsResponseDefaultTypeInternal() {}
  union {
    EnumeratePermissionsResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnumeratePermissionsResponseDefaultTypeInternal _EnumeratePermissionsResponse_default_instance_;
}  // namespace permission
}  // namespace ottx
static ::_pb::Metadata file_level_metadata_permission_5fservice_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_permission_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_permission_5fservice_2eproto = nullptr;

const uint32_t TableStruct_permission_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::AppKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::AppKey, _impl_.app_),
  PROTOBUF_FIELD_OFFSET(::ottx::permission::AppKey, _impl_.syndication_partner_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::EnumeratePermissionsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::EnumeratePermissionsRequest, _impl_.app_key_),
  PROTOBUF_FIELD_OFFSET(::ottx::permission::EnumeratePermissionsRequest, _impl_.permission_filters_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::EnumeratePermissionsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ottx::permission::EnumeratePermissionsResponse, _impl_.permissions_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ottx::permission::AppKey)},
  { 8, -1, -1, sizeof(::ottx::permission::EnumeratePermissionsRequest)},
  { 16, -1, -1, sizeof(::ottx::permission::EnumeratePermissionsResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ottx::permission::_AppKey_default_instance_._instance,
  &::ottx::permission::_EnumeratePermissionsRequest_default_instance_._instance,
  &::ottx::permission::_EnumeratePermissionsResponse_default_instance_._instance,
};

const char descriptor_table_protodef_permission_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030permission_service.proto\022\017ottx.permiss"
  "ion\"5\n\006AppKey\022\013\n\003app\030\001 \001(\t\022\036\n\026syndicatio"
  "n_partner_id\030\002 \001(\t\"c\n\033EnumeratePermissio"
  "nsRequest\022(\n\007app_key\030\001 \001(\0132\027.ottx.permis"
  "sion.AppKey\022\032\n\022permission_filters\030\002 \003(\t\""
  "3\n\034EnumeratePermissionsResponse\022\023\n\013permi"
  "ssions\030\001 \003(\t2\214\001\n\025AppPermissionsService\022s"
  "\n\024EnumeratePermissions\022,.ottx.permission"
  ".EnumeratePermissionsRequest\032-.ottx.perm"
  "ission.EnumeratePermissionsResponseb\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_permission_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_permission_5fservice_2eproto = {
    false, false, 403, descriptor_table_protodef_permission_5fservice_2eproto,
    "permission_service.proto",
    &descriptor_table_permission_5fservice_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_permission_5fservice_2eproto::offsets,
    file_level_metadata_permission_5fservice_2eproto, file_level_enum_descriptors_permission_5fservice_2eproto,
    file_level_service_descriptors_permission_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_permission_5fservice_2eproto_getter() {
  return &descriptor_table_permission_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_permission_5fservice_2eproto(&descriptor_table_permission_5fservice_2eproto);
namespace ottx {
namespace permission {

// ===================================================================

class AppKey::_Internal {
 public:
};

AppKey::AppKey(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ottx.permission.AppKey)
}
AppKey::AppKey(const AppKey& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AppKey* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.app_){}
    , decltype(_impl_.syndication_partner_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.app_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app().empty()) {
    _this->_impl_.app_.Set(from._internal_app(), 
      _this->GetArenaForAllocation());
  }
  _impl_.syndication_partner_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.syndication_partner_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_syndication_partner_id().empty()) {
    _this->_impl_.syndication_partner_id_.Set(from._internal_syndication_partner_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ottx.permission.AppKey)
}

inline void AppKey::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.app_){}
    , decltype(_impl_.syndication_partner_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.app_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.syndication_partner_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.syndication_partner_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AppKey::~AppKey() {
  // @@protoc_insertion_point(destructor:ottx.permission.AppKey)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AppKey::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.app_.Destroy();
  _impl_.syndication_partner_id_.Destroy();
}

void AppKey::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AppKey::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.permission.AppKey)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.app_.ClearToEmpty();
  _impl_.syndication_partner_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AppKey::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string app = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_app();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ottx.permission.AppKey.app"));
        } else
          goto handle_unusual;
        continue;
      // string syndication_partner_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_syndication_partner_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ottx.permission.AppKey.syndication_partner_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AppKey::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.permission.AppKey)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string app = 1;
  if (!this->_internal_app().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app().data(), static_cast<int>(this->_internal_app().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.permission.AppKey.app");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_app(), target);
  }

  // string syndication_partner_id = 2;
  if (!this->_internal_syndication_partner_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_syndication_partner_id().data(), static_cast<int>(this->_internal_syndication_partner_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.permission.AppKey.syndication_partner_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_syndication_partner_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.permission.AppKey)
  return target;
}

size_t AppKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.permission.AppKey)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string app = 1;
  if (!this->_internal_app().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app());
  }

  // string syndication_partner_id = 2;
  if (!this->_internal_syndication_partner_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_syndication_partner_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AppKey::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AppKey::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AppKey::GetClassData() const { return &_class_data_; }


void AppKey::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AppKey*>(&to_msg);
  auto& from = static_cast<const AppKey&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ottx.permission.AppKey)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_app().empty()) {
    _this->_internal_set_app(from._internal_app());
  }
  if (!from._internal_syndication_partner_id().empty()) {
    _this->_internal_set_syndication_partner_id(from._internal_syndication_partner_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AppKey::CopyFrom(const AppKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.permission.AppKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppKey::IsInitialized() const {
  return true;
}

void AppKey::InternalSwap(AppKey* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.app_, lhs_arena,
      &other->_impl_.app_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.syndication_partner_id_, lhs_arena,
      &other->_impl_.syndication_partner_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata AppKey::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_permission_5fservice_2eproto_getter, &descriptor_table_permission_5fservice_2eproto_once,
      file_level_metadata_permission_5fservice_2eproto[0]);
}

// ===================================================================

class EnumeratePermissionsRequest::_Internal {
 public:
  static const ::ottx::permission::AppKey& app_key(const EnumeratePermissionsRequest* msg);
};

const ::ottx::permission::AppKey&
EnumeratePermissionsRequest::_Internal::app_key(const EnumeratePermissionsRequest* msg) {
  return *msg->_impl_.app_key_;
}
EnumeratePermissionsRequest::EnumeratePermissionsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ottx.permission.EnumeratePermissionsRequest)
}
EnumeratePermissionsRequest::EnumeratePermissionsRequest(const EnumeratePermissionsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EnumeratePermissionsRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.permission_filters_){from._impl_.permission_filters_}
    , decltype(_impl_.app_key_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_app_key()) {
    _this->_impl_.app_key_ = new ::ottx::permission::AppKey(*from._impl_.app_key_);
  }
  // @@protoc_insertion_point(copy_constructor:ottx.permission.EnumeratePermissionsRequest)
}

inline void EnumeratePermissionsRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.permission_filters_){arena}
    , decltype(_impl_.app_key_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EnumeratePermissionsRequest::~EnumeratePermissionsRequest() {
  // @@protoc_insertion_point(destructor:ottx.permission.EnumeratePermissionsRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EnumeratePermissionsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.permission_filters_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.app_key_;
}

void EnumeratePermissionsRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EnumeratePermissionsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.permission.EnumeratePermissionsRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.permission_filters_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.app_key_ != nullptr) {
    delete _impl_.app_key_;
  }
  _impl_.app_key_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnumeratePermissionsRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ottx.permission.AppKey app_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_app_key(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string permission_filters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_permission_filters();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ottx.permission.EnumeratePermissionsRequest.permission_filters"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EnumeratePermissionsRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.permission.EnumeratePermissionsRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ottx.permission.AppKey app_key = 1;
  if (this->_internal_has_app_key()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::app_key(this),
        _Internal::app_key(this).GetCachedSize(), target, stream);
  }

  // repeated string permission_filters = 2;
  for (int i = 0, n = this->_internal_permission_filters_size(); i < n; i++) {
    const auto& s = this->_internal_permission_filters(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.permission.EnumeratePermissionsRequest.permission_filters");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.permission.EnumeratePermissionsRequest)
  return target;
}

size_t EnumeratePermissionsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.permission.EnumeratePermissionsRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string permission_filters = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.permission_filters_.size());
  for (int i = 0, n = _impl_.permission_filters_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.permission_filters_.Get(i));
  }

  // .ottx.permission.AppKey app_key = 1;
  if (this->_internal_has_app_key()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.app_key_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EnumeratePermissionsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EnumeratePermissionsRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EnumeratePermissionsRequest::GetClassData() const { return &_class_data_; }


void EnumeratePermissionsRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EnumeratePermissionsRequest*>(&to_msg);
  auto& from = static_cast<const EnumeratePermissionsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ottx.permission.EnumeratePermissionsRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.permission_filters_.MergeFrom(from._impl_.permission_filters_);
  if (from._internal_has_app_key()) {
    _this->_internal_mutable_app_key()->::ottx::permission::AppKey::MergeFrom(
        from._internal_app_key());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EnumeratePermissionsRequest::CopyFrom(const EnumeratePermissionsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.permission.EnumeratePermissionsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnumeratePermissionsRequest::IsInitialized() const {
  return true;
}

void EnumeratePermissionsRequest::InternalSwap(EnumeratePermissionsRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.permission_filters_.InternalSwap(&other->_impl_.permission_filters_);
  swap(_impl_.app_key_, other->_impl_.app_key_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EnumeratePermissionsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_permission_5fservice_2eproto_getter, &descriptor_table_permission_5fservice_2eproto_once,
      file_level_metadata_permission_5fservice_2eproto[1]);
}

// ===================================================================

class EnumeratePermissionsResponse::_Internal {
 public:
};

EnumeratePermissionsResponse::EnumeratePermissionsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ottx.permission.EnumeratePermissionsResponse)
}
EnumeratePermissionsResponse::EnumeratePermissionsResponse(const EnumeratePermissionsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EnumeratePermissionsResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.permissions_){from._impl_.permissions_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ottx.permission.EnumeratePermissionsResponse)
}

inline void EnumeratePermissionsResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.permissions_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EnumeratePermissionsResponse::~EnumeratePermissionsResponse() {
  // @@protoc_insertion_point(destructor:ottx.permission.EnumeratePermissionsResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EnumeratePermissionsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.permissions_.~RepeatedPtrField();
}

void EnumeratePermissionsResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EnumeratePermissionsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ottx.permission.EnumeratePermissionsResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.permissions_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EnumeratePermissionsResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string permissions = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_permissions();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ottx.permission.EnumeratePermissionsResponse.permissions"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EnumeratePermissionsResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ottx.permission.EnumeratePermissionsResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string permissions = 1;
  for (int i = 0, n = this->_internal_permissions_size(); i < n; i++) {
    const auto& s = this->_internal_permissions(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ottx.permission.EnumeratePermissionsResponse.permissions");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ottx.permission.EnumeratePermissionsResponse)
  return target;
}

size_t EnumeratePermissionsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ottx.permission.EnumeratePermissionsResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string permissions = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.permissions_.size());
  for (int i = 0, n = _impl_.permissions_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.permissions_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EnumeratePermissionsResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EnumeratePermissionsResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EnumeratePermissionsResponse::GetClassData() const { return &_class_data_; }


void EnumeratePermissionsResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EnumeratePermissionsResponse*>(&to_msg);
  auto& from = static_cast<const EnumeratePermissionsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ottx.permission.EnumeratePermissionsResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.permissions_.MergeFrom(from._impl_.permissions_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EnumeratePermissionsResponse::CopyFrom(const EnumeratePermissionsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ottx.permission.EnumeratePermissionsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnumeratePermissionsResponse::IsInitialized() const {
  return true;
}

void EnumeratePermissionsResponse::InternalSwap(EnumeratePermissionsResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.permissions_.InternalSwap(&other->_impl_.permissions_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EnumeratePermissionsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_permission_5fservice_2eproto_getter, &descriptor_table_permission_5fservice_2eproto_once,
      file_level_metadata_permission_5fservice_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace permission
}  // namespace ottx
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ottx::permission::AppKey*
Arena::CreateMaybeMessage< ::ottx::permission::AppKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::permission::AppKey >(arena);
}
template<> PROTOBUF_NOINLINE ::ottx::permission::EnumeratePermissionsRequest*
Arena::CreateMaybeMessage< ::ottx::permission::EnumeratePermissionsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::permission::EnumeratePermissionsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ottx::permission::EnumeratePermissionsResponse*
Arena::CreateMaybeMessage< ::ottx::permission::EnumeratePermissionsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ottx::permission::EnumeratePermissionsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
