#pragma once

#define FIREBOLT_INTERFACE_OFFSET                                              \
  (RPC::IDS::ID_EXTERNAL_INTERFACE_OFFSET + 0x2000)

namespace WPEFramework {

namespace Exchange {

enum IDS_COMCAST_FB : uint32_t {

  ID_FBMETRICS = FIREBOLT_INTERFACE_OFFSET,

        ID_APP_GATEWAY  = FIREBOLT_INTERFACE_OFFSET + 0x010,
        ID_APP_GATEWAY_RESPONDER = ID_APP_GATEWAY + 1,
        ID_APP_GATEWAY_AUTHENTICATOR = ID_APP_GATEWAY + 2,
        ID_APP_GATEWAY_REQUEST_HANDLER = ID_APP_GATEWAY + 3,

        ID_APP_NOTIFICATIONS  = FIREBOLT_INTERFACE_OFFSET + 0x020,
        ID_APP_NOTIFICATIONS_HANDLER_INTERNAL = ID_APP_NOTIFICATIONS + 1,

  ID_APP2APP_PROVIDER = FIREBOLT_INTERFACE_OFFSET + 0x030,

  ID_FBPRIVACY = FIREBOLT_INTERFACE_OFFSET + 0x040,
  ID_FBPRIVACY_NOTIFICATION = ID_FBPRIVACY + 1,

  ID_LAUNCHDELEGATE = FIREBOLT_INTERFACE_OFFSET + 0x050,
  ID_LAUNCHDELEGATE_NOTIFICATION = ID_LAUNCHDELEGATE + 1,

  ID_FBASLINCHPIN = FIREBOLT_INTERFACE_OFFSET + 0x060,
  ID_FBASLINCHPIN_NOTIFICATION = ID_FBASLINCHPIN + 1,

  ID_XVP_SESSION = FIREBOLT_INTERFACE_OFFSET + 0x070,
  ID_XVP_XIFA = FIREBOLT_INTERFACE_OFFSET + 0x080,
  ID_XVP_PLAYBACK = FIREBOLT_INTERFACE_OFFSET + 0x090,
  ID_XVP_VIDEO = FIREBOLT_INTERFACE_OFFSET + 0x0A0,

  ID_FBDISCOVERY = FIREBOLT_INTERFACE_OFFSET + 0x0B0,

  ID_FBADVERTISING = FIREBOLT_INTERFACE_OFFSET + 0x0C0,

  ID_FBSETTINGS = FIREBOLT_INTERFACE_OFFSET + 0x0D0,

  ID_BADGER = FIREBOLT_INTERFACE_OFFSET + 0x0E0,

  ID_OTT_SERVICES = FIREBOLT_INTERFACE_OFFSET + 0x0F0

 };
}
} // namespace WPEFramework