// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permission_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_permission_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_permission_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_permission_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_permission_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_permission_5fservice_2eproto;
namespace ottx {
namespace permission {
class AppKey;
struct AppKeyDefaultTypeInternal;
extern AppKeyDefaultTypeInternal _AppKey_default_instance_;
class EnumeratePermissionsRequest;
struct EnumeratePermissionsRequestDefaultTypeInternal;
extern EnumeratePermissionsRequestDefaultTypeInternal _EnumeratePermissionsRequest_default_instance_;
class EnumeratePermissionsResponse;
struct EnumeratePermissionsResponseDefaultTypeInternal;
extern EnumeratePermissionsResponseDefaultTypeInternal _EnumeratePermissionsResponse_default_instance_;
}  // namespace permission
}  // namespace ottx
PROTOBUF_NAMESPACE_OPEN
template<> ::ottx::permission::AppKey* Arena::CreateMaybeMessage<::ottx::permission::AppKey>(Arena*);
template<> ::ottx::permission::EnumeratePermissionsRequest* Arena::CreateMaybeMessage<::ottx::permission::EnumeratePermissionsRequest>(Arena*);
template<> ::ottx::permission::EnumeratePermissionsResponse* Arena::CreateMaybeMessage<::ottx::permission::EnumeratePermissionsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ottx {
namespace permission {

// ===================================================================

class AppKey final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.permission.AppKey) */ {
 public:
  inline AppKey() : AppKey(nullptr) {}
  ~AppKey() override;
  explicit constexpr AppKey(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppKey(const AppKey& from);
  AppKey(AppKey&& from) noexcept
    : AppKey() {
    *this = ::std::move(from);
  }

  inline AppKey& operator=(const AppKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppKey& operator=(AppKey&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppKey& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppKey* internal_default_instance() {
    return reinterpret_cast<const AppKey*>(
               &_AppKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AppKey& a, AppKey& b) {
    a.Swap(&b);
  }
  inline void Swap(AppKey* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppKey* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppKey* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppKey>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppKey& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AppKey& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppKey* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.permission.AppKey";
  }
  protected:
  explicit AppKey(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppFieldNumber = 1,
    kSyndicationPartnerIdFieldNumber = 2,
  };
  // string app = 1;
  void clear_app();
  const std::string& app() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app();
  PROTOBUF_NODISCARD std::string* release_app();
  void set_allocated_app(std::string* app);
  private:
  const std::string& _internal_app() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app(const std::string& value);
  std::string* _internal_mutable_app();
  public:

  // string syndication_partner_id = 2;
  void clear_syndication_partner_id();
  const std::string& syndication_partner_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_syndication_partner_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_syndication_partner_id();
  PROTOBUF_NODISCARD std::string* release_syndication_partner_id();
  void set_allocated_syndication_partner_id(std::string* syndication_partner_id);
  private:
  const std::string& _internal_syndication_partner_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_syndication_partner_id(const std::string& value);
  std::string* _internal_mutable_syndication_partner_id();
  public:

  // @@protoc_insertion_point(class_scope:ottx.permission.AppKey)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr syndication_partner_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_permission_5fservice_2eproto;
};
// -------------------------------------------------------------------

class EnumeratePermissionsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.permission.EnumeratePermissionsRequest) */ {
 public:
  inline EnumeratePermissionsRequest() : EnumeratePermissionsRequest(nullptr) {}
  ~EnumeratePermissionsRequest() override;
  explicit constexpr EnumeratePermissionsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnumeratePermissionsRequest(const EnumeratePermissionsRequest& from);
  EnumeratePermissionsRequest(EnumeratePermissionsRequest&& from) noexcept
    : EnumeratePermissionsRequest() {
    *this = ::std::move(from);
  }

  inline EnumeratePermissionsRequest& operator=(const EnumeratePermissionsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnumeratePermissionsRequest& operator=(EnumeratePermissionsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnumeratePermissionsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnumeratePermissionsRequest* internal_default_instance() {
    return reinterpret_cast<const EnumeratePermissionsRequest*>(
               &_EnumeratePermissionsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EnumeratePermissionsRequest& a, EnumeratePermissionsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EnumeratePermissionsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnumeratePermissionsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnumeratePermissionsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EnumeratePermissionsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnumeratePermissionsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EnumeratePermissionsRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnumeratePermissionsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.permission.EnumeratePermissionsRequest";
  }
  protected:
  explicit EnumeratePermissionsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPermissionFiltersFieldNumber = 2,
    kAppKeyFieldNumber = 1,
  };
  // repeated string permission_filters = 2;
  int permission_filters_size() const;
  private:
  int _internal_permission_filters_size() const;
  public:
  void clear_permission_filters();
  const std::string& permission_filters(int index) const;
  std::string* mutable_permission_filters(int index);
  void set_permission_filters(int index, const std::string& value);
  void set_permission_filters(int index, std::string&& value);
  void set_permission_filters(int index, const char* value);
  void set_permission_filters(int index, const char* value, size_t size);
  std::string* add_permission_filters();
  void add_permission_filters(const std::string& value);
  void add_permission_filters(std::string&& value);
  void add_permission_filters(const char* value);
  void add_permission_filters(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& permission_filters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_permission_filters();
  private:
  const std::string& _internal_permission_filters(int index) const;
  std::string* _internal_add_permission_filters();
  public:

  // .ottx.permission.AppKey app_key = 1;
  bool has_app_key() const;
  private:
  bool _internal_has_app_key() const;
  public:
  void clear_app_key();
  const ::ottx::permission::AppKey& app_key() const;
  PROTOBUF_NODISCARD ::ottx::permission::AppKey* release_app_key();
  ::ottx::permission::AppKey* mutable_app_key();
  void set_allocated_app_key(::ottx::permission::AppKey* app_key);
  private:
  const ::ottx::permission::AppKey& _internal_app_key() const;
  ::ottx::permission::AppKey* _internal_mutable_app_key();
  public:
  void unsafe_arena_set_allocated_app_key(
      ::ottx::permission::AppKey* app_key);
  ::ottx::permission::AppKey* unsafe_arena_release_app_key();

  // @@protoc_insertion_point(class_scope:ottx.permission.EnumeratePermissionsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> permission_filters_;
  ::ottx::permission::AppKey* app_key_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_permission_5fservice_2eproto;
};
// -------------------------------------------------------------------

class EnumeratePermissionsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.permission.EnumeratePermissionsResponse) */ {
 public:
  inline EnumeratePermissionsResponse() : EnumeratePermissionsResponse(nullptr) {}
  ~EnumeratePermissionsResponse() override;
  explicit constexpr EnumeratePermissionsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EnumeratePermissionsResponse(const EnumeratePermissionsResponse& from);
  EnumeratePermissionsResponse(EnumeratePermissionsResponse&& from) noexcept
    : EnumeratePermissionsResponse() {
    *this = ::std::move(from);
  }

  inline EnumeratePermissionsResponse& operator=(const EnumeratePermissionsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnumeratePermissionsResponse& operator=(EnumeratePermissionsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnumeratePermissionsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnumeratePermissionsResponse* internal_default_instance() {
    return reinterpret_cast<const EnumeratePermissionsResponse*>(
               &_EnumeratePermissionsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EnumeratePermissionsResponse& a, EnumeratePermissionsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(EnumeratePermissionsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnumeratePermissionsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnumeratePermissionsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EnumeratePermissionsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EnumeratePermissionsResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EnumeratePermissionsResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnumeratePermissionsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.permission.EnumeratePermissionsResponse";
  }
  protected:
  explicit EnumeratePermissionsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPermissionsFieldNumber = 1,
  };
  // repeated string permissions = 1;
  int permissions_size() const;
  private:
  int _internal_permissions_size() const;
  public:
  void clear_permissions();
  const std::string& permissions(int index) const;
  std::string* mutable_permissions(int index);
  void set_permissions(int index, const std::string& value);
  void set_permissions(int index, std::string&& value);
  void set_permissions(int index, const char* value);
  void set_permissions(int index, const char* value, size_t size);
  std::string* add_permissions();
  void add_permissions(const std::string& value);
  void add_permissions(std::string&& value);
  void add_permissions(const char* value);
  void add_permissions(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& permissions() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_permissions();
  private:
  const std::string& _internal_permissions(int index) const;
  std::string* _internal_add_permissions();
  public:

  // @@protoc_insertion_point(class_scope:ottx.permission.EnumeratePermissionsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> permissions_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_permission_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AppKey

// string app = 1;
inline void AppKey::clear_app() {
  app_.ClearToEmpty();
}
inline const std::string& AppKey::app() const {
  // @@protoc_insertion_point(field_get:ottx.permission.AppKey.app)
  return _internal_app();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AppKey::set_app(ArgT0&& arg0, ArgT... args) {
 
 app_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.permission.AppKey.app)
}
inline std::string* AppKey::mutable_app() {
  std::string* _s = _internal_mutable_app();
  // @@protoc_insertion_point(field_mutable:ottx.permission.AppKey.app)
  return _s;
}
inline const std::string& AppKey::_internal_app() const {
  return app_.Get();
}
inline void AppKey::_internal_set_app(const std::string& value) {
  
  app_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AppKey::_internal_mutable_app() {
  
  return app_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AppKey::release_app() {
  // @@protoc_insertion_point(field_release:ottx.permission.AppKey.app)
  return app_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AppKey::set_allocated_app(std::string* app) {
  if (app != nullptr) {
    
  } else {
    
  }
  app_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (app_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    app_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.permission.AppKey.app)
}

// string syndication_partner_id = 2;
inline void AppKey::clear_syndication_partner_id() {
  syndication_partner_id_.ClearToEmpty();
}
inline const std::string& AppKey::syndication_partner_id() const {
  // @@protoc_insertion_point(field_get:ottx.permission.AppKey.syndication_partner_id)
  return _internal_syndication_partner_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AppKey::set_syndication_partner_id(ArgT0&& arg0, ArgT... args) {
 
 syndication_partner_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.permission.AppKey.syndication_partner_id)
}
inline std::string* AppKey::mutable_syndication_partner_id() {
  std::string* _s = _internal_mutable_syndication_partner_id();
  // @@protoc_insertion_point(field_mutable:ottx.permission.AppKey.syndication_partner_id)
  return _s;
}
inline const std::string& AppKey::_internal_syndication_partner_id() const {
  return syndication_partner_id_.Get();
}
inline void AppKey::_internal_set_syndication_partner_id(const std::string& value) {
  
  syndication_partner_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AppKey::_internal_mutable_syndication_partner_id() {
  
  return syndication_partner_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AppKey::release_syndication_partner_id() {
  // @@protoc_insertion_point(field_release:ottx.permission.AppKey.syndication_partner_id)
  return syndication_partner_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AppKey::set_allocated_syndication_partner_id(std::string* syndication_partner_id) {
  if (syndication_partner_id != nullptr) {
    
  } else {
    
  }
  syndication_partner_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), syndication_partner_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (syndication_partner_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    syndication_partner_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.permission.AppKey.syndication_partner_id)
}

// -------------------------------------------------------------------

// EnumeratePermissionsRequest

// .ottx.permission.AppKey app_key = 1;
inline bool EnumeratePermissionsRequest::_internal_has_app_key() const {
  return this != internal_default_instance() && app_key_ != nullptr;
}
inline bool EnumeratePermissionsRequest::has_app_key() const {
  return _internal_has_app_key();
}
inline void EnumeratePermissionsRequest::clear_app_key() {
  if (GetArenaForAllocation() == nullptr && app_key_ != nullptr) {
    delete app_key_;
  }
  app_key_ = nullptr;
}
inline const ::ottx::permission::AppKey& EnumeratePermissionsRequest::_internal_app_key() const {
  const ::ottx::permission::AppKey* p = app_key_;
  return p != nullptr ? *p : reinterpret_cast<const ::ottx::permission::AppKey&>(
      ::ottx::permission::_AppKey_default_instance_);
}
inline const ::ottx::permission::AppKey& EnumeratePermissionsRequest::app_key() const {
  // @@protoc_insertion_point(field_get:ottx.permission.EnumeratePermissionsRequest.app_key)
  return _internal_app_key();
}
inline void EnumeratePermissionsRequest::unsafe_arena_set_allocated_app_key(
    ::ottx::permission::AppKey* app_key) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(app_key_);
  }
  app_key_ = app_key;
  if (app_key) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ottx.permission.EnumeratePermissionsRequest.app_key)
}
inline ::ottx::permission::AppKey* EnumeratePermissionsRequest::release_app_key() {
  
  ::ottx::permission::AppKey* temp = app_key_;
  app_key_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::ottx::permission::AppKey* EnumeratePermissionsRequest::unsafe_arena_release_app_key() {
  // @@protoc_insertion_point(field_release:ottx.permission.EnumeratePermissionsRequest.app_key)
  
  ::ottx::permission::AppKey* temp = app_key_;
  app_key_ = nullptr;
  return temp;
}
inline ::ottx::permission::AppKey* EnumeratePermissionsRequest::_internal_mutable_app_key() {
  
  if (app_key_ == nullptr) {
    auto* p = CreateMaybeMessage<::ottx::permission::AppKey>(GetArenaForAllocation());
    app_key_ = p;
  }
  return app_key_;
}
inline ::ottx::permission::AppKey* EnumeratePermissionsRequest::mutable_app_key() {
  ::ottx::permission::AppKey* _msg = _internal_mutable_app_key();
  // @@protoc_insertion_point(field_mutable:ottx.permission.EnumeratePermissionsRequest.app_key)
  return _msg;
}
inline void EnumeratePermissionsRequest::set_allocated_app_key(::ottx::permission::AppKey* app_key) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete app_key_;
  }
  if (app_key) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::ottx::permission::AppKey>::GetOwningArena(app_key);
    if (message_arena != submessage_arena) {
      app_key = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, app_key, submessage_arena);
    }
    
  } else {
    
  }
  app_key_ = app_key;
  // @@protoc_insertion_point(field_set_allocated:ottx.permission.EnumeratePermissionsRequest.app_key)
}

// repeated string permission_filters = 2;
inline int EnumeratePermissionsRequest::_internal_permission_filters_size() const {
  return permission_filters_.size();
}
inline int EnumeratePermissionsRequest::permission_filters_size() const {
  return _internal_permission_filters_size();
}
inline void EnumeratePermissionsRequest::clear_permission_filters() {
  permission_filters_.Clear();
}
inline std::string* EnumeratePermissionsRequest::add_permission_filters() {
  std::string* _s = _internal_add_permission_filters();
  // @@protoc_insertion_point(field_add_mutable:ottx.permission.EnumeratePermissionsRequest.permission_filters)
  return _s;
}
inline const std::string& EnumeratePermissionsRequest::_internal_permission_filters(int index) const {
  return permission_filters_.Get(index);
}
inline const std::string& EnumeratePermissionsRequest::permission_filters(int index) const {
  // @@protoc_insertion_point(field_get:ottx.permission.EnumeratePermissionsRequest.permission_filters)
  return _internal_permission_filters(index);
}
inline std::string* EnumeratePermissionsRequest::mutable_permission_filters(int index) {
  // @@protoc_insertion_point(field_mutable:ottx.permission.EnumeratePermissionsRequest.permission_filters)
  return permission_filters_.Mutable(index);
}
inline void EnumeratePermissionsRequest::set_permission_filters(int index, const std::string& value) {
  permission_filters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::set_permission_filters(int index, std::string&& value) {
  permission_filters_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::set_permission_filters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  permission_filters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::set_permission_filters(int index, const char* value, size_t size) {
  permission_filters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline std::string* EnumeratePermissionsRequest::_internal_add_permission_filters() {
  return permission_filters_.Add();
}
inline void EnumeratePermissionsRequest::add_permission_filters(const std::string& value) {
  permission_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::add_permission_filters(std::string&& value) {
  permission_filters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::add_permission_filters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  permission_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline void EnumeratePermissionsRequest::add_permission_filters(const char* value, size_t size) {
  permission_filters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ottx.permission.EnumeratePermissionsRequest.permission_filters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
EnumeratePermissionsRequest::permission_filters() const {
  // @@protoc_insertion_point(field_list:ottx.permission.EnumeratePermissionsRequest.permission_filters)
  return permission_filters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
EnumeratePermissionsRequest::mutable_permission_filters() {
  // @@protoc_insertion_point(field_mutable_list:ottx.permission.EnumeratePermissionsRequest.permission_filters)
  return &permission_filters_;
}

// -------------------------------------------------------------------

// EnumeratePermissionsResponse

// repeated string permissions = 1;
inline int EnumeratePermissionsResponse::_internal_permissions_size() const {
  return permissions_.size();
}
inline int EnumeratePermissionsResponse::permissions_size() const {
  return _internal_permissions_size();
}
inline void EnumeratePermissionsResponse::clear_permissions() {
  permissions_.Clear();
}
inline std::string* EnumeratePermissionsResponse::add_permissions() {
  std::string* _s = _internal_add_permissions();
  // @@protoc_insertion_point(field_add_mutable:ottx.permission.EnumeratePermissionsResponse.permissions)
  return _s;
}
inline const std::string& EnumeratePermissionsResponse::_internal_permissions(int index) const {
  return permissions_.Get(index);
}
inline const std::string& EnumeratePermissionsResponse::permissions(int index) const {
  // @@protoc_insertion_point(field_get:ottx.permission.EnumeratePermissionsResponse.permissions)
  return _internal_permissions(index);
}
inline std::string* EnumeratePermissionsResponse::mutable_permissions(int index) {
  // @@protoc_insertion_point(field_mutable:ottx.permission.EnumeratePermissionsResponse.permissions)
  return permissions_.Mutable(index);
}
inline void EnumeratePermissionsResponse::set_permissions(int index, const std::string& value) {
  permissions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::set_permissions(int index, std::string&& value) {
  permissions_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::set_permissions(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  permissions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::set_permissions(int index, const char* value, size_t size) {
  permissions_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline std::string* EnumeratePermissionsResponse::_internal_add_permissions() {
  return permissions_.Add();
}
inline void EnumeratePermissionsResponse::add_permissions(const std::string& value) {
  permissions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::add_permissions(std::string&& value) {
  permissions_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::add_permissions(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  permissions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline void EnumeratePermissionsResponse::add_permissions(const char* value, size_t size) {
  permissions_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ottx.permission.EnumeratePermissionsResponse.permissions)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
EnumeratePermissionsResponse::permissions() const {
  // @@protoc_insertion_point(field_list:ottx.permission.EnumeratePermissionsResponse.permissions)
  return permissions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
EnumeratePermissionsResponse::mutable_permissions() {
  // @@protoc_insertion_point(field_mutable_list:ottx.permission.EnumeratePermissionsResponse.permissions)
  return &permissions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace permission
}  // namespace ottx

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_permission_5fservice_2eproto
