// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ott_token.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ott_5ftoken_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ott_5ftoken_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ott_5ftoken_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ott_5ftoken_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ott_5ftoken_2eproto;
namespace ottx {
namespace otttoken {
class AuthTokenRequest;
struct AuthTokenRequestDefaultTypeInternal;
extern AuthTokenRequestDefaultTypeInternal _AuthTokenRequest_default_instance_;
class AuthTokenResponse;
struct AuthTokenResponseDefaultTypeInternal;
extern AuthTokenResponseDefaultTypeInternal _AuthTokenResponse_default_instance_;
class PlatformTokenRequest;
struct PlatformTokenRequestDefaultTypeInternal;
extern PlatformTokenRequestDefaultTypeInternal _PlatformTokenRequest_default_instance_;
class PlatformTokenResponse;
struct PlatformTokenResponseDefaultTypeInternal;
extern PlatformTokenResponseDefaultTypeInternal _PlatformTokenResponse_default_instance_;
}  // namespace otttoken
}  // namespace ottx
PROTOBUF_NAMESPACE_OPEN
template<> ::ottx::otttoken::AuthTokenRequest* Arena::CreateMaybeMessage<::ottx::otttoken::AuthTokenRequest>(Arena*);
template<> ::ottx::otttoken::AuthTokenResponse* Arena::CreateMaybeMessage<::ottx::otttoken::AuthTokenResponse>(Arena*);
template<> ::ottx::otttoken::PlatformTokenRequest* Arena::CreateMaybeMessage<::ottx::otttoken::PlatformTokenRequest>(Arena*);
template<> ::ottx::otttoken::PlatformTokenResponse* Arena::CreateMaybeMessage<::ottx::otttoken::PlatformTokenResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ottx {
namespace otttoken {

// ===================================================================

class AuthTokenRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.otttoken.AuthTokenRequest) */ {
 public:
  inline AuthTokenRequest() : AuthTokenRequest(nullptr) {}
  ~AuthTokenRequest() override;
  explicit constexpr AuthTokenRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AuthTokenRequest(const AuthTokenRequest& from);
  AuthTokenRequest(AuthTokenRequest&& from) noexcept
    : AuthTokenRequest() {
    *this = ::std::move(from);
  }

  inline AuthTokenRequest& operator=(const AuthTokenRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthTokenRequest& operator=(AuthTokenRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthTokenRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthTokenRequest* internal_default_instance() {
    return reinterpret_cast<const AuthTokenRequest*>(
               &_AuthTokenRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AuthTokenRequest& a, AuthTokenRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AuthTokenRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthTokenRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthTokenRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AuthTokenRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AuthTokenRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AuthTokenRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AuthTokenRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.otttoken.AuthTokenRequest";
  }
  protected:
  explicit AuthTokenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPartnerIdFieldNumber = 1,
    kAppIdFieldNumber = 2,
    kXsctFieldNumber = 3,
    kSatFieldNumber = 4,
  };
  // string partner_id = 1;
  void clear_partner_id();
  const std::string& partner_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_partner_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_partner_id();
  PROTOBUF_NODISCARD std::string* release_partner_id();
  void set_allocated_partner_id(std::string* partner_id);
  private:
  const std::string& _internal_partner_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_partner_id(const std::string& value);
  std::string* _internal_mutable_partner_id();
  public:

  // string app_id = 2;
  void clear_app_id();
  const std::string& app_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app_id();
  PROTOBUF_NODISCARD std::string* release_app_id();
  void set_allocated_app_id(std::string* app_id);
  private:
  const std::string& _internal_app_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_id(const std::string& value);
  std::string* _internal_mutable_app_id();
  public:

  // string xsct = 3;
  void clear_xsct();
  const std::string& xsct() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_xsct(ArgT0&& arg0, ArgT... args);
  std::string* mutable_xsct();
  PROTOBUF_NODISCARD std::string* release_xsct();
  void set_allocated_xsct(std::string* xsct);
  private:
  const std::string& _internal_xsct() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_xsct(const std::string& value);
  std::string* _internal_mutable_xsct();
  public:

  // string sat = 4;
  void clear_sat();
  const std::string& sat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sat();
  PROTOBUF_NODISCARD std::string* release_sat();
  void set_allocated_sat(std::string* sat);
  private:
  const std::string& _internal_sat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sat(const std::string& value);
  std::string* _internal_mutable_sat();
  public:

  // @@protoc_insertion_point(class_scope:ottx.otttoken.AuthTokenRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr partner_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr xsct_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ott_5ftoken_2eproto;
};
// -------------------------------------------------------------------

class AuthTokenResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.otttoken.AuthTokenResponse) */ {
 public:
  inline AuthTokenResponse() : AuthTokenResponse(nullptr) {}
  ~AuthTokenResponse() override;
  explicit constexpr AuthTokenResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AuthTokenResponse(const AuthTokenResponse& from);
  AuthTokenResponse(AuthTokenResponse&& from) noexcept
    : AuthTokenResponse() {
    *this = ::std::move(from);
  }

  inline AuthTokenResponse& operator=(const AuthTokenResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthTokenResponse& operator=(AuthTokenResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthTokenResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthTokenResponse* internal_default_instance() {
    return reinterpret_cast<const AuthTokenResponse*>(
               &_AuthTokenResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AuthTokenResponse& a, AuthTokenResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AuthTokenResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthTokenResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthTokenResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AuthTokenResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AuthTokenResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AuthTokenResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AuthTokenResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.otttoken.AuthTokenResponse";
  }
  protected:
  explicit AuthTokenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccessTokenFieldNumber = 1,
    kTokenTypeFieldNumber = 2,
    kScopeFieldNumber = 3,
    kExpiresInFieldNumber = 4,
  };
  // string access_token = 1;
  void clear_access_token();
  const std::string& access_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_access_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_access_token();
  PROTOBUF_NODISCARD std::string* release_access_token();
  void set_allocated_access_token(std::string* access_token);
  private:
  const std::string& _internal_access_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_access_token(const std::string& value);
  std::string* _internal_mutable_access_token();
  public:

  // string token_type = 2;
  void clear_token_type();
  const std::string& token_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token_type();
  PROTOBUF_NODISCARD std::string* release_token_type();
  void set_allocated_token_type(std::string* token_type);
  private:
  const std::string& _internal_token_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token_type(const std::string& value);
  std::string* _internal_mutable_token_type();
  public:

  // string scope = 3;
  void clear_scope();
  const std::string& scope() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_scope(ArgT0&& arg0, ArgT... args);
  std::string* mutable_scope();
  PROTOBUF_NODISCARD std::string* release_scope();
  void set_allocated_scope(std::string* scope);
  private:
  const std::string& _internal_scope() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scope(const std::string& value);
  std::string* _internal_mutable_scope();
  public:

  // int32 expires_in = 4;
  void clear_expires_in();
  int32_t expires_in() const;
  void set_expires_in(int32_t value);
  private:
  int32_t _internal_expires_in() const;
  void _internal_set_expires_in(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ottx.otttoken.AuthTokenResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr access_token_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr scope_;
  int32_t expires_in_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ott_5ftoken_2eproto;
};
// -------------------------------------------------------------------

class PlatformTokenRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.otttoken.PlatformTokenRequest) */ {
 public:
  inline PlatformTokenRequest() : PlatformTokenRequest(nullptr) {}
  ~PlatformTokenRequest() override;
  explicit constexpr PlatformTokenRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlatformTokenRequest(const PlatformTokenRequest& from);
  PlatformTokenRequest(PlatformTokenRequest&& from) noexcept
    : PlatformTokenRequest() {
    *this = ::std::move(from);
  }

  inline PlatformTokenRequest& operator=(const PlatformTokenRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlatformTokenRequest& operator=(PlatformTokenRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlatformTokenRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlatformTokenRequest* internal_default_instance() {
    return reinterpret_cast<const PlatformTokenRequest*>(
               &_PlatformTokenRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlatformTokenRequest& a, PlatformTokenRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PlatformTokenRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlatformTokenRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlatformTokenRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlatformTokenRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlatformTokenRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PlatformTokenRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlatformTokenRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.otttoken.PlatformTokenRequest";
  }
  protected:
  explicit PlatformTokenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXactFieldNumber = 1,
    kSatFieldNumber = 2,
    kAppIdFieldNumber = 3,
  };
  // string xact = 1;
  void clear_xact();
  const std::string& xact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_xact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_xact();
  PROTOBUF_NODISCARD std::string* release_xact();
  void set_allocated_xact(std::string* xact);
  private:
  const std::string& _internal_xact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_xact(const std::string& value);
  std::string* _internal_mutable_xact();
  public:

  // string sat = 2;
  void clear_sat();
  const std::string& sat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sat();
  PROTOBUF_NODISCARD std::string* release_sat();
  void set_allocated_sat(std::string* sat);
  private:
  const std::string& _internal_sat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sat(const std::string& value);
  std::string* _internal_mutable_sat();
  public:

  // string app_id = 3;
  void clear_app_id();
  const std::string& app_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app_id();
  PROTOBUF_NODISCARD std::string* release_app_id();
  void set_allocated_app_id(std::string* app_id);
  private:
  const std::string& _internal_app_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_id(const std::string& value);
  std::string* _internal_mutable_app_id();
  public:

  // @@protoc_insertion_point(class_scope:ottx.otttoken.PlatformTokenRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr xact_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sat_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ott_5ftoken_2eproto;
};
// -------------------------------------------------------------------

class PlatformTokenResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ottx.otttoken.PlatformTokenResponse) */ {
 public:
  inline PlatformTokenResponse() : PlatformTokenResponse(nullptr) {}
  ~PlatformTokenResponse() override;
  explicit constexpr PlatformTokenResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlatformTokenResponse(const PlatformTokenResponse& from);
  PlatformTokenResponse(PlatformTokenResponse&& from) noexcept
    : PlatformTokenResponse() {
    *this = ::std::move(from);
  }

  inline PlatformTokenResponse& operator=(const PlatformTokenResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlatformTokenResponse& operator=(PlatformTokenResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlatformTokenResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlatformTokenResponse* internal_default_instance() {
    return reinterpret_cast<const PlatformTokenResponse*>(
               &_PlatformTokenResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlatformTokenResponse& a, PlatformTokenResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PlatformTokenResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlatformTokenResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlatformTokenResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlatformTokenResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlatformTokenResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PlatformTokenResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlatformTokenResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ottx.otttoken.PlatformTokenResponse";
  }
  protected:
  explicit PlatformTokenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlatformTokenFieldNumber = 1,
    kTokenTypeFieldNumber = 2,
    kScopeFieldNumber = 4,
    kExpiresInFieldNumber = 3,
  };
  // string platform_token = 1;
  void clear_platform_token();
  const std::string& platform_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_platform_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_platform_token();
  PROTOBUF_NODISCARD std::string* release_platform_token();
  void set_allocated_platform_token(std::string* platform_token);
  private:
  const std::string& _internal_platform_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_platform_token(const std::string& value);
  std::string* _internal_mutable_platform_token();
  public:

  // string token_type = 2;
  void clear_token_type();
  const std::string& token_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token_type();
  PROTOBUF_NODISCARD std::string* release_token_type();
  void set_allocated_token_type(std::string* token_type);
  private:
  const std::string& _internal_token_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token_type(const std::string& value);
  std::string* _internal_mutable_token_type();
  public:

  // string scope = 4;
  void clear_scope();
  const std::string& scope() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_scope(ArgT0&& arg0, ArgT... args);
  std::string* mutable_scope();
  PROTOBUF_NODISCARD std::string* release_scope();
  void set_allocated_scope(std::string* scope);
  private:
  const std::string& _internal_scope() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scope(const std::string& value);
  std::string* _internal_mutable_scope();
  public:

  // int32 expires_in = 3;
  void clear_expires_in();
  int32_t expires_in() const;
  void set_expires_in(int32_t value);
  private:
  int32_t _internal_expires_in() const;
  void _internal_set_expires_in(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ottx.otttoken.PlatformTokenResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr platform_token_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr scope_;
  int32_t expires_in_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ott_5ftoken_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AuthTokenRequest

// string partner_id = 1;
inline void AuthTokenRequest::clear_partner_id() {
  partner_id_.ClearToEmpty();
}
inline const std::string& AuthTokenRequest::partner_id() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenRequest.partner_id)
  return _internal_partner_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenRequest::set_partner_id(ArgT0&& arg0, ArgT... args) {
 
 partner_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenRequest.partner_id)
}
inline std::string* AuthTokenRequest::mutable_partner_id() {
  std::string* _s = _internal_mutable_partner_id();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenRequest.partner_id)
  return _s;
}
inline const std::string& AuthTokenRequest::_internal_partner_id() const {
  return partner_id_.Get();
}
inline void AuthTokenRequest::_internal_set_partner_id(const std::string& value) {
  
  partner_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::_internal_mutable_partner_id() {
  
  return partner_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::release_partner_id() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenRequest.partner_id)
  return partner_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenRequest::set_allocated_partner_id(std::string* partner_id) {
  if (partner_id != nullptr) {
    
  } else {
    
  }
  partner_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), partner_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (partner_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    partner_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenRequest.partner_id)
}

// string app_id = 2;
inline void AuthTokenRequest::clear_app_id() {
  app_id_.ClearToEmpty();
}
inline const std::string& AuthTokenRequest::app_id() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenRequest.app_id)
  return _internal_app_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenRequest::set_app_id(ArgT0&& arg0, ArgT... args) {
 
 app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenRequest.app_id)
}
inline std::string* AuthTokenRequest::mutable_app_id() {
  std::string* _s = _internal_mutable_app_id();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenRequest.app_id)
  return _s;
}
inline const std::string& AuthTokenRequest::_internal_app_id() const {
  return app_id_.Get();
}
inline void AuthTokenRequest::_internal_set_app_id(const std::string& value) {
  
  app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::_internal_mutable_app_id() {
  
  return app_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::release_app_id() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenRequest.app_id)
  return app_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenRequest::set_allocated_app_id(std::string* app_id) {
  if (app_id != nullptr) {
    
  } else {
    
  }
  app_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (app_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenRequest.app_id)
}

// string xsct = 3;
inline void AuthTokenRequest::clear_xsct() {
  xsct_.ClearToEmpty();
}
inline const std::string& AuthTokenRequest::xsct() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenRequest.xsct)
  return _internal_xsct();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenRequest::set_xsct(ArgT0&& arg0, ArgT... args) {
 
 xsct_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenRequest.xsct)
}
inline std::string* AuthTokenRequest::mutable_xsct() {
  std::string* _s = _internal_mutable_xsct();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenRequest.xsct)
  return _s;
}
inline const std::string& AuthTokenRequest::_internal_xsct() const {
  return xsct_.Get();
}
inline void AuthTokenRequest::_internal_set_xsct(const std::string& value) {
  
  xsct_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::_internal_mutable_xsct() {
  
  return xsct_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::release_xsct() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenRequest.xsct)
  return xsct_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenRequest::set_allocated_xsct(std::string* xsct) {
  if (xsct != nullptr) {
    
  } else {
    
  }
  xsct_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), xsct,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (xsct_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    xsct_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenRequest.xsct)
}

// string sat = 4;
inline void AuthTokenRequest::clear_sat() {
  sat_.ClearToEmpty();
}
inline const std::string& AuthTokenRequest::sat() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenRequest.sat)
  return _internal_sat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenRequest::set_sat(ArgT0&& arg0, ArgT... args) {
 
 sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenRequest.sat)
}
inline std::string* AuthTokenRequest::mutable_sat() {
  std::string* _s = _internal_mutable_sat();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenRequest.sat)
  return _s;
}
inline const std::string& AuthTokenRequest::_internal_sat() const {
  return sat_.Get();
}
inline void AuthTokenRequest::_internal_set_sat(const std::string& value) {
  
  sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::_internal_mutable_sat() {
  
  return sat_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenRequest::release_sat() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenRequest.sat)
  return sat_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenRequest::set_allocated_sat(std::string* sat) {
  if (sat != nullptr) {
    
  } else {
    
  }
  sat_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sat,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sat_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenRequest.sat)
}

// -------------------------------------------------------------------

// AuthTokenResponse

// string access_token = 1;
inline void AuthTokenResponse::clear_access_token() {
  access_token_.ClearToEmpty();
}
inline const std::string& AuthTokenResponse::access_token() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenResponse.access_token)
  return _internal_access_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenResponse::set_access_token(ArgT0&& arg0, ArgT... args) {
 
 access_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenResponse.access_token)
}
inline std::string* AuthTokenResponse::mutable_access_token() {
  std::string* _s = _internal_mutable_access_token();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenResponse.access_token)
  return _s;
}
inline const std::string& AuthTokenResponse::_internal_access_token() const {
  return access_token_.Get();
}
inline void AuthTokenResponse::_internal_set_access_token(const std::string& value) {
  
  access_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::_internal_mutable_access_token() {
  
  return access_token_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::release_access_token() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenResponse.access_token)
  return access_token_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenResponse::set_allocated_access_token(std::string* access_token) {
  if (access_token != nullptr) {
    
  } else {
    
  }
  access_token_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), access_token,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (access_token_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    access_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenResponse.access_token)
}

// string token_type = 2;
inline void AuthTokenResponse::clear_token_type() {
  token_type_.ClearToEmpty();
}
inline const std::string& AuthTokenResponse::token_type() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenResponse.token_type)
  return _internal_token_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenResponse::set_token_type(ArgT0&& arg0, ArgT... args) {
 
 token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenResponse.token_type)
}
inline std::string* AuthTokenResponse::mutable_token_type() {
  std::string* _s = _internal_mutable_token_type();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenResponse.token_type)
  return _s;
}
inline const std::string& AuthTokenResponse::_internal_token_type() const {
  return token_type_.Get();
}
inline void AuthTokenResponse::_internal_set_token_type(const std::string& value) {
  
  token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::_internal_mutable_token_type() {
  
  return token_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::release_token_type() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenResponse.token_type)
  return token_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenResponse::set_allocated_token_type(std::string* token_type) {
  if (token_type != nullptr) {
    
  } else {
    
  }
  token_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), token_type,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_type_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenResponse.token_type)
}

// string scope = 3;
inline void AuthTokenResponse::clear_scope() {
  scope_.ClearToEmpty();
}
inline const std::string& AuthTokenResponse::scope() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenResponse.scope)
  return _internal_scope();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AuthTokenResponse::set_scope(ArgT0&& arg0, ArgT... args) {
 
 scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenResponse.scope)
}
inline std::string* AuthTokenResponse::mutable_scope() {
  std::string* _s = _internal_mutable_scope();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.AuthTokenResponse.scope)
  return _s;
}
inline const std::string& AuthTokenResponse::_internal_scope() const {
  return scope_.Get();
}
inline void AuthTokenResponse::_internal_set_scope(const std::string& value) {
  
  scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::_internal_mutable_scope() {
  
  return scope_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* AuthTokenResponse::release_scope() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.AuthTokenResponse.scope)
  return scope_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void AuthTokenResponse::set_allocated_scope(std::string* scope) {
  if (scope != nullptr) {
    
  } else {
    
  }
  scope_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), scope,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (scope_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.AuthTokenResponse.scope)
}

// int32 expires_in = 4;
inline void AuthTokenResponse::clear_expires_in() {
  expires_in_ = 0;
}
inline int32_t AuthTokenResponse::_internal_expires_in() const {
  return expires_in_;
}
inline int32_t AuthTokenResponse::expires_in() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.AuthTokenResponse.expires_in)
  return _internal_expires_in();
}
inline void AuthTokenResponse::_internal_set_expires_in(int32_t value) {
  
  expires_in_ = value;
}
inline void AuthTokenResponse::set_expires_in(int32_t value) {
  _internal_set_expires_in(value);
  // @@protoc_insertion_point(field_set:ottx.otttoken.AuthTokenResponse.expires_in)
}

// -------------------------------------------------------------------

// PlatformTokenRequest

// string xact = 1;
inline void PlatformTokenRequest::clear_xact() {
  xact_.ClearToEmpty();
}
inline const std::string& PlatformTokenRequest::xact() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenRequest.xact)
  return _internal_xact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenRequest::set_xact(ArgT0&& arg0, ArgT... args) {
 
 xact_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenRequest.xact)
}
inline std::string* PlatformTokenRequest::mutable_xact() {
  std::string* _s = _internal_mutable_xact();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenRequest.xact)
  return _s;
}
inline const std::string& PlatformTokenRequest::_internal_xact() const {
  return xact_.Get();
}
inline void PlatformTokenRequest::_internal_set_xact(const std::string& value) {
  
  xact_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::_internal_mutable_xact() {
  
  return xact_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::release_xact() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenRequest.xact)
  return xact_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenRequest::set_allocated_xact(std::string* xact) {
  if (xact != nullptr) {
    
  } else {
    
  }
  xact_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), xact,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (xact_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    xact_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenRequest.xact)
}

// string sat = 2;
inline void PlatformTokenRequest::clear_sat() {
  sat_.ClearToEmpty();
}
inline const std::string& PlatformTokenRequest::sat() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenRequest.sat)
  return _internal_sat();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenRequest::set_sat(ArgT0&& arg0, ArgT... args) {
 
 sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenRequest.sat)
}
inline std::string* PlatformTokenRequest::mutable_sat() {
  std::string* _s = _internal_mutable_sat();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenRequest.sat)
  return _s;
}
inline const std::string& PlatformTokenRequest::_internal_sat() const {
  return sat_.Get();
}
inline void PlatformTokenRequest::_internal_set_sat(const std::string& value) {
  
  sat_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::_internal_mutable_sat() {
  
  return sat_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::release_sat() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenRequest.sat)
  return sat_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenRequest::set_allocated_sat(std::string* sat) {
  if (sat != nullptr) {
    
  } else {
    
  }
  sat_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sat,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sat_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenRequest.sat)
}

// string app_id = 3;
inline void PlatformTokenRequest::clear_app_id() {
  app_id_.ClearToEmpty();
}
inline const std::string& PlatformTokenRequest::app_id() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenRequest.app_id)
  return _internal_app_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenRequest::set_app_id(ArgT0&& arg0, ArgT... args) {
 
 app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenRequest.app_id)
}
inline std::string* PlatformTokenRequest::mutable_app_id() {
  std::string* _s = _internal_mutable_app_id();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenRequest.app_id)
  return _s;
}
inline const std::string& PlatformTokenRequest::_internal_app_id() const {
  return app_id_.Get();
}
inline void PlatformTokenRequest::_internal_set_app_id(const std::string& value) {
  
  app_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::_internal_mutable_app_id() {
  
  return app_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenRequest::release_app_id() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenRequest.app_id)
  return app_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenRequest::set_allocated_app_id(std::string* app_id) {
  if (app_id != nullptr) {
    
  } else {
    
  }
  app_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (app_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    app_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenRequest.app_id)
}

// -------------------------------------------------------------------

// PlatformTokenResponse

// string platform_token = 1;
inline void PlatformTokenResponse::clear_platform_token() {
  platform_token_.ClearToEmpty();
}
inline const std::string& PlatformTokenResponse::platform_token() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenResponse.platform_token)
  return _internal_platform_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenResponse::set_platform_token(ArgT0&& arg0, ArgT... args) {
 
 platform_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenResponse.platform_token)
}
inline std::string* PlatformTokenResponse::mutable_platform_token() {
  std::string* _s = _internal_mutable_platform_token();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenResponse.platform_token)
  return _s;
}
inline const std::string& PlatformTokenResponse::_internal_platform_token() const {
  return platform_token_.Get();
}
inline void PlatformTokenResponse::_internal_set_platform_token(const std::string& value) {
  
  platform_token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::_internal_mutable_platform_token() {
  
  return platform_token_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::release_platform_token() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenResponse.platform_token)
  return platform_token_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenResponse::set_allocated_platform_token(std::string* platform_token) {
  if (platform_token != nullptr) {
    
  } else {
    
  }
  platform_token_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), platform_token,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (platform_token_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    platform_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenResponse.platform_token)
}

// string token_type = 2;
inline void PlatformTokenResponse::clear_token_type() {
  token_type_.ClearToEmpty();
}
inline const std::string& PlatformTokenResponse::token_type() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenResponse.token_type)
  return _internal_token_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenResponse::set_token_type(ArgT0&& arg0, ArgT... args) {
 
 token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenResponse.token_type)
}
inline std::string* PlatformTokenResponse::mutable_token_type() {
  std::string* _s = _internal_mutable_token_type();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenResponse.token_type)
  return _s;
}
inline const std::string& PlatformTokenResponse::_internal_token_type() const {
  return token_type_.Get();
}
inline void PlatformTokenResponse::_internal_set_token_type(const std::string& value) {
  
  token_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::_internal_mutable_token_type() {
  
  return token_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::release_token_type() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenResponse.token_type)
  return token_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenResponse::set_allocated_token_type(std::string* token_type) {
  if (token_type != nullptr) {
    
  } else {
    
  }
  token_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), token_type,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_type_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    token_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenResponse.token_type)
}

// int32 expires_in = 3;
inline void PlatformTokenResponse::clear_expires_in() {
  expires_in_ = 0;
}
inline int32_t PlatformTokenResponse::_internal_expires_in() const {
  return expires_in_;
}
inline int32_t PlatformTokenResponse::expires_in() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenResponse.expires_in)
  return _internal_expires_in();
}
inline void PlatformTokenResponse::_internal_set_expires_in(int32_t value) {
  
  expires_in_ = value;
}
inline void PlatformTokenResponse::set_expires_in(int32_t value) {
  _internal_set_expires_in(value);
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenResponse.expires_in)
}

// string scope = 4;
inline void PlatformTokenResponse::clear_scope() {
  scope_.ClearToEmpty();
}
inline const std::string& PlatformTokenResponse::scope() const {
  // @@protoc_insertion_point(field_get:ottx.otttoken.PlatformTokenResponse.scope)
  return _internal_scope();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlatformTokenResponse::set_scope(ArgT0&& arg0, ArgT... args) {
 
 scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ottx.otttoken.PlatformTokenResponse.scope)
}
inline std::string* PlatformTokenResponse::mutable_scope() {
  std::string* _s = _internal_mutable_scope();
  // @@protoc_insertion_point(field_mutable:ottx.otttoken.PlatformTokenResponse.scope)
  return _s;
}
inline const std::string& PlatformTokenResponse::_internal_scope() const {
  return scope_.Get();
}
inline void PlatformTokenResponse::_internal_set_scope(const std::string& value) {
  
  scope_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::_internal_mutable_scope() {
  
  return scope_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PlatformTokenResponse::release_scope() {
  // @@protoc_insertion_point(field_release:ottx.otttoken.PlatformTokenResponse.scope)
  return scope_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PlatformTokenResponse::set_allocated_scope(std::string* scope) {
  if (scope != nullptr) {
    
  } else {
    
  }
  scope_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), scope,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (scope_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    scope_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ottx.otttoken.PlatformTokenResponse.scope)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace otttoken
}  // namespace ottx

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ott_5ftoken_2eproto
